### ISSUE TITLE
Add new evaluation context value for "Variables"

### ISSUE THREAD

**Issue by weinand** [microsoft/debug-adapter-protocol#100]
see https://github.com/microsoft/vscode/issues/69768:

The DAP client "VS Code" already sends a `variables` context value for the `evaluate` request that is used to populate the VARIABLES view. This usage is perfectly in line with `evaluate` requests used to populate the WATCHES view (which receive a `watches` context).
  
Since the `variables` value is not documented we should add it to the DAP spec.

**Comment by weinand** [comment]
@isidorn in exactly what situation(s) is an `evaluate` request with context `variables` used? 
Correct me if I'm wrong but it seems to be only used for the "copy to clipboard" functionality and not to populate the view, right? (for populating the view we have the `variables` request).

If this is true, then a `variables` context is no longer needed if we introduce a `copyToClipboard` context (see https://github.com/microsoft/debug-adapter-protocol/issues/29).

**Comment by isidorn** [comment]
@weinand you are correct. The variables is only used for the copy to clipboard.
So I suggest that we do not introduce it to the DAP. And I will fully stop sending it - hopefully no extension was realying on this since it was not part of the protocol.

**Comment by weinand** [comment]
@isidorn Yes, we will not introduce it to the DAP, but you must continue to send it iff `capabilities.supportsClipboardContext` is falsy. 
If `capabilities.supportsClipboardContext` is true, you are sending the `clipboard` anyway.

**Comment by isidorn** [comment]
Makes perfect sense. That is how we are behaving now on master.
Code pointer https://github.com/microsoft/vscode/blob/e4cf6e1e4868badc1a7790ae403f35bfab66a943/src/vs/workbench/contrib/debug/browser/debugActions.ts#L403

**Comment by weinand** [comment]
Nothing to do for DAP.
