### ISSUE TITLE
Correct sequence for single-evaluation languages?

### ISSUE THREAD

**Issue by nickbattle** [microsoft/debug-adapter-protocol#101]
I'm looking into whether it is possible to create LSP/DAP support for the suite of VDM dialects.  Interpreters for VDM need to evaluate a single expression and return a result, so I'm trying to work out how to support that with DAP request/replies.

I think I can extend a launch request to carry language-specific details, including an expression to evaluate. But I can't see a natural way to send the overall result of an evaluation back to the client - it would need to be an arbitrary value, not a numeric exit code.

Presumably other languages must have this requirement. How is this normally done?

**Comment by nickbattle** [comment]
The closest I can find in the DAP specification is the "evaluate" request (with a REPL context). But these requests would also have to be used from (say) a breakpoint to evaluate expressions in the local context. So is it permissible to have one "long running" evaluate request for the overall execution, with nested evaluates and responses within that at a breakpoint stop?

**Comment by connor4312** [comment]
If the launch takes a single expression, maybe sending the result back in an `output` event prior to exiting would work for you?

**Comment by nickbattle** [comment]
Thanks @connor4312. That would presumably "work" in a visual sense, but I wondered whether there was an accepted way to do this.  At the moment I'm using "evaluate" requests, but I haven't yet implemented breakpoint stops, so I don't know whether nesting them will work (I'm developing with lsp4e).

**Comment by weinand** [comment]
@nickbattle if a debug adapter implements the `evaluate` request correctly, nested `evaluate` requests should work just fine.

**Comment by nickbattle** [comment]
> @nickbattle if a debug adapter implements the `evaluate` request correctly, nested `evaluate` requests should work just fine.

OK, thanks @weinand, it does seem to work correctly in lsp4e. I've not tried VS code yet.

**Comment by nickbattle** [comment]
> This issue has been closed because it represents a question. Questions are better addressed on [StackOverflow](https://stackoverflow.com/questions/tagged/debug-adapter-protocol).

That isn't a recognised tag on StackOverflow @weinand ?
