### ISSUE TITLE
DAP Output event category for logpoint messages

### ISSUE THREAD

**Issue by tomcec** [microsoft/debug-adapter-protocol#107]
Hi, what category in output event https://microsoft.github.io/debug-adapter-protocol/specification#Events_Output should be used for logpoint messages https://code.visualstudio.com/blogs/2018/07/12/introducing-logpoints-and-auto-attach#_introducing-logpoints ?

**Comment by weinand** [comment]
It does not really matter, but I suggest to rely on the default (which is `console`).
