### ISSUE TITLE
Encoding problem with Debug Adapter Protocol

### ISSUE THREAD

**Issue by caboom04** [microsoft/debug-adapter-protocol#119]
- VSCode Version:1.45.1
- OS Version:Windows 7

I'm debugging with my Debug Server which implement Debug Adapter Protocol。The source code is encoding with GB2312. There are some chinese comments, and VSCode send a ExpressionRequest with some chinese characters when hover over the comments. But the 'content length' is not matched with the real length of the contents, so my Debug Server can not resolve the request.

I guess, it is because when VSCode generate the request, 'content length' equals the string length, but not the UTF-8 buffer length.

**Comment by ishche** [comment]
![image](https://user-images.githubusercontent.com/590426/83855441-5bd59880-a718-11ea-923d-a9904e4b6678.png)
It should be in bites.

**Comment by caboom04** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/590426/83855441-5bd59880-a718-11ea-923d-a9904e4b6678.png)
> It should be in bites.

In the Debug Server, I read Content-Length and ‘\r\n’ first, and then read characters one by one. If the request contains chinese, I cannot get enough characters as the Content-Length says. It is blocked until next request come(comes more characters).
It works fine if there are no chinese characters.

**Comment by ishche** [comment]
> It works fine if there are no chinese characters.

It makes sense. [1 character >= 1 byte](https://stackoverflow.com/questions/10229156/how-many-characters-can-utf-8-encode) in UTF-8.

**Comment by caboom04** [comment]
> 
> 
> > It works fine if there are no chinese characters.
> 
> It makes sense. [1 character != 1 byte](https://stackoverflow.com/questions/10229156/how-many-characters-can-utf-8-encode) in UTF-8.

Thanks. Found the problem.
I develop the Debug Server with C#. I read characters by Console.Read() function, and convert result to byte anytime. But sometimes it is more than one byte.
