### ISSUE TITLE
Debug adapter protocol: Allow for breakpoints to resolve to multiple locations

### ISSUE THREAD

**Issue by ebluestein** [microsoft/debug-adapter-protocol#13]
Currently, the protocol allows the debug adapter to respond to a SetBreakpoints request with a response that contains a Breakpoint (https://github.com/Microsoft/vscode-debugadapter-node/blob/master/protocol/src/debugProtocol.ts#L1462)

Breakpoint, if representing a Verified breakpoint, has a single notion of the breakpoint's resolved location.  But for many debug adapters, a single breakpoint might actually resolve to n locations.  This is especially true for native debuggers where a function in a header file might be inlined all over the program. 

The debug adapter can maintain this mapping internally and not share it with the UX, but then the user can't accurately see the location(s) a breakpoint resolved to. 

Would it be possible to add something like an optional array of resolved locations to Breakpoint? Maybe something like:

  ```
export interface BreakpointLocation {
      /** The source where the breakpoint is located. */
      source?: Source;
      /** The start line of the actual range covered by the breakpoint. */
      line?: number;
      /** An optional start column of the actual range covered by the breakpoint. */
      column?: number;
      /** An optional end line of the actual range covered by the breakpoint. */
      endLine?: number;
      /** An optional end column of the actual range covered by the breakpoint. If no end line is given, then the end column is assumed to be in the start line. */
      endColumn?: number;
  }
```

**Comment by tromey** [comment]
I wonder if this is a dup of #114.  That one has a more complete proposal in it.

Anyway, this problem came up during the gdb DAP implementation.  Currently gdb will just report the first location, but that's not really very good -- the IDE may want to display some marker at all the locations, not just the first one.
