### ISSUE TITLE
[Clarify] Optional property behaviour: omit vs null

### ISSUE THREAD

**Issue by puremourning** [microsoft/debug-adapter-protocol#130]
My understanding from the specification is that an optional properpty of a message object may be omitted, or may be supplied with one of the valid types. For example(;

```typescript
  /**
   * If sourceReference > 0 the contents of the source must be retrieved through the SourceRequest (even if a path is specified).
   * A sourceReference is only valid for a session, so it must not be used to persist a source.
   * The value should be less than or equal to 2147483647 (2^31 - 1).
   */
  sourceReference?: number;

```

For the above item, `sourceReference` may be _omitted_ from the message but if supplied _must_ be of type `number`. And importantly _may not_ be supplied as `null`.

If `null` were valid, the specification would be written as:

```typescript
  /**
   * If sourceReference > 0 the contents of the source must be retrieved through the SourceRequest (even if a path is specified).
   * A sourceReference is only valid for a session, so it must not be used to persist a source.
   * The value should be less than or equal to 2147483647 (2^31 - 1).
   */
  sourceReference?: number | null;
```

(Correct?)

Certainly it seems that's the behaviour of most servers and would be a reasonable assumption for a client to make.

Could we clarify in the specification that is the case (or that it isn't and clients and servers are expected to assume `null` is a valid value for all optional properties)?

**Comment by weinand** [comment]
`null` is only a valid value if explicitly specified in a type definition.
To the contrary `undefined` is a valid value for an optional property even if it is not explicitly specified in a type definition.

E.g. with the type definition `sourceReference?: number` the property may be either omitted or set to a value of `undefined`.

**Comment by puremourning** [comment]
> E.g. with the type definition sourceReference?: number the property may be either omitted or set to a value of undefined.

Is `undefined` specified in JSON ?! I thought that there was no `undefined` in JSON

**Comment by weinand** [comment]
@puremourning  yes, you are right. `undefined` is a JS thing...

So I should have said:
`null` is only a valid value if explicitly specified in a type definition; it can not be used as a value for an omitted property.

**Comment by puremourning** [comment]
Thanks that’s what I thought. :)
