### ISSUE TITLE
Clarify documentation on when and where the 'text' for StoppedEvent shows up in the UI

### ISSUE THREAD

**Issue by polinasok** [microsoft/debug-adapter-protocol#135]
My goal is to implement a StoppedEvent when a go program stops due to a segfault. I am considering setting the event's reason to 'exception' or maybe something more custom, but in either case I need a way to report the detailed error to the user. The spec says 
```
   /**
     * Additional information. E.g. if reason is 'exception', text contains the exception name. This string is shown in the UI.
     */
    text?: string;
```
I am setting 'text' in the event I send to the client:
```
[-> to client]{"seq":0,"type":"event","event":"stopped","body":{"reason":"exception","threadId":1,"text":"bad access","allThreadsStopped":true}}
```
But I do not see it displayed anywhere in the UI, including when I hover as suggested in https://github.com/Microsoft/vscode/issues/3101
![image](https://user-images.githubusercontent.com/51177946/89862703-5b64de00-db5d-11ea-980b-26258f25f450.png)
Is this feature still operational? Should it work with any reason? Where should it appear? The only related issue I found is https://github.com/microsoft/vscode/issues/63416, which suggests that this feature worked a while back, but doesn't offer any screenshots with the details.

**Comment by weinand** [comment]
@polinasok the DAP spec does not know what exact UI a DAP client uses. So the description of the "text" property is accurate.
If you do not see the "text" showing up anywhere in VS Code, then it makes sense to create an issue against VS Code.
BTW, please note that DAP has a `ExceptionInfo` request to provide additional information about an exception. 

@isidorn where does VS Code show the "text" property? Is it on hover?

**Comment by isidorn** [comment]
It is shown on the hover of the "PAUSED ON EXCEPTION" element.
Code pointer https://github.com/microsoft/vscode/blob/8a57c4cef7f55dd9b542e20b7a561351126cf2ff/src/vs/workbench/contrib/debug/browser/callStackView.ts#L160

**Comment by hyangah** [comment]
FYI when debugging javascript, I couldn't hover of the `PAUSED ON EXCEPTION` because [the 'profile' button](https://github.com/microsoft/vscode-docs/blob/a21fa6fa94d2e319ba48e3b6fe1e5067fb5ce35a/release-notes/v1_45.md#new-javascript-debugger) always appears and interferes. But I do see some exception details in the code section. Not sure though if that's from the `ExceptionInfo` response or the `text` property. 
<img width="1384" alt="Screen Shot 2020-08-11 at 7 57 30 PM" src="https://user-images.githubusercontent.com/4999471/89965650-4c446580-dc1b-11ea-96c4-004e4ee78e48.png">

**Comment by weinand** [comment]
@hyangah the exception details are coming from the `ExceptionInfo` request.

@isidorn are you aware of the "profile"button interaction?

**Comment by isidorn** [comment]
@weinand @hyangah I missed the "profile" button interaction.
A workaround would be to show it as hover over the whole session element. Currently on hover it just says "Session" which is not that useful. What do you think?
