### ISSUE TITLE
threadId and stackFrameId fields in InvalidatedEvent defined as "number" instead of "integer"

### ISSUE THREAD

**Issue by jonahgraham** [microsoft/debug-adapter-protocol#145]
The new event added in 1.42 (Invalidate) has inconsistent types for the threadId and stackFrameId.

https://github.com/microsoft/debug-adapter-protocol/blob/fdaa68760ff4c22dab619b1dbb8cfa8f80b6966f/debugAdapterProtocol.json#L672-L678

The other threadIds and stackFrameIds in the protocol are defined as integer instead of number.

I assume this was a simple oversight as the typescript generated version uses number in both cases.

**Comment by weinand** [comment]
@jonahgraham great find, thanks.
