### ISSUE TITLE
Clarify percentage precision

### ISSUE THREAD

**Issue by KamasamaK** [microsoft/debug-adapter-protocol#148]
In the [Language Server Protocol](https://github.com/microsoft/language-server-protocol/issues/1037#issuecomment-722186589), `percentage` is now specified as "uinteger in the range [0, 100]" but in DAP it's just specified as `number` in the [schema](https://github.com/microsoft/debug-adapter-protocol/blob/05df55b42ebac2811c6bbe2ec5fcc49604c7f5ec/debugAdapterProtocol.json#L582). Even though they're separate protocols, I think it makes sense to have some consistency with these features since many of the same clients will probably be supporting both with a common capability. It has come up before that sometimes `integer` is intended instead of `number`, so I want to verify that this is intentional. If so, I will bring this up in LSP since that change is not finalized yet.

**Comment by weinand** [comment]
Yes, using the type "number" (and a range 0-100 in the comment) was intentional.
