### ISSUE TITLE
Debug protocol: support side effect flags on expressions

### ISSUE THREAD

**Issue by jacdavis** [microsoft/debug-adapter-protocol#152]
In order to use the debug protocol in VS and Xamerin, we need the ability to differentiate between expressions that contain side effects and those that don't. In VS, for instance, the expression evaluator being used by the debugger can mark an expression as side effect free, therefore, safe for implicit evaluation, and non-side effect free evaluations.  As mentioned above, this is primarily used to determine if an expression is safe to re-evaluate at each break mode, or if it should only evaluate once. Examples of expressions with side effects:
I=3;
Foo();
Examples of expressions without side effects:
squild.length where length is a property getter (still requiring func-eval but safe). 

An optional flag on the evaluation result and the the variables result would be sufficient.

**Comment by weinand** [comment]
Variables have a 'hasSideEffects' property.
