### ISSUE TITLE
support a "don't care" for `cwd` in the `runInTerminal` request

### ISSUE THREAD

**Issue by weinand** [microsoft/debug-adapter-protocol#160]
Since the `cwd` property of the `runInTerminal` request is not optional, it is not possible to express the "don't care" case, e.g. if a DA knows that the "cwd" is already correct and that there is  no need to generate a `cd ...` command.

**Comment by puremourning** [comment]
how about just sending `.` ?

**Comment by weinand** [comment]
A cwd `.` will still result in a `cd .;`

**Comment by puremourning** [comment]
not in my client. I don't really understand where the `cd .` is coming from... ? There's no requirement for the client to issue that as a command in the terminal.

**Comment by weinand** [comment]
Depending on the implementation of `runInTerminal` in the client, it might be necessary to ensure that the debuggee is launched in the specified `cwd`. For example if the terminal is reused across  debug launches, and two projects have different working directories.

**Comment by gregg-miskelly** [comment]
Both VS Code (so far I have tested Linux and Windows) and VS are happy with empty string. Anyone have a client which isn't?

**Comment by puremourning** [comment]
In case it helps...

* up until yesterday, vimspector would give [an obnoxious error](https://github.com/puremourning/vimspector/blame/5b8883791934194ea6822c0a631941230aa8e6e6/python3/vimspector/terminal.py#L20) if server sent an invalid path for cwd. I happened to find a buggy server that happened to misbehave, so I changed it yesterday https://github.com/puremourning/vimspector/blame/master/python3/vimspector/terminal.py#L21
* vim-dap would probably break if I read this correctly https://github.com/dradtke/vim-dap/blob/f15a8b869bca5951936dcdddd4a262c34d7f518d/autoload/dap.vim#L574
* nvim-dap apparently ignores cwd https://github.com/mfussenegger/nvim-dap/blob/926b049d7200ec7f0c69e5bcb6cbfa737207cafb/lua/dap.lua#L243-L253
* I checked dap-mode but I can't elisp enough to be sure one way or another https://github.com/emacs-lsp/dap-mode/blob/8b7cbc68904036c211f29420c24cac82e74d817a/dap-mode.el#L974.

I suspect that any other client would reasonably expect the value supplied to be a valid path.

**Comment by weinand** [comment]
Since I don't want to introduce a new capability for this ancillary feature, I propose to change the `cwd` comment to the following:
```js
  /**
   * Working directory for the command. For non-empty, valid paths this typically results in execution of a change directory command ("cd cwd"). 
   */
  cwd: string;
```

**Comment by gregg-miskelly** [comment]
LGTM
