### ISSUE TITLE
Make the "Content-Length" header optional

### ISSUE THREAD

**Issue by adriancuadrado** [microsoft/debug-adapter-protocol#168]
All JSON objects start with an opening curly bracket and end with a closing one. Why would you want to know how may bytes are sent if you have to read until the closing curly bracket anyways?

I would like to suggest that when the first character of the first header is an opening curly braket you assume what follows is the content part of the request. This way the spec remains backward-compatible. If you want to use any header just make sure the very first character is not '{'. If that condition is met, then the request contains headers.

Pseudocode:
```
// If the request doesn't have headers.
if(request.startsWith('{')) {
  return readJsonObject(request);
} else {
  headers = readHeaders(request);
  return readContentPart(request, headers.contentLength);
}
```

Comments? thoughts? opinions?

**Comment by connor4312** [comment]
👎 from me.

- It may be backwards-compatible but will still cause compatibility issues. If it's permitted, then either the client or the debug adapter could decide to omit the header, and if the other side has not been updated to deal with a missing content-length header it will break.
    -For other features in DAP we use the capabilities, but checking for this capability would require some new, separate out-of-bounds signalling
- It requires the use of a streaming JSON parser. Notably, JavaScript does not have one natively. While there are modules that implement streaming parsing they are much slower than the highly-optimized native JSON.parse.
- Even for other languages or those with streaming JSON support, knowing the content length ahead of time allow them to deal with memory more efficiently.

The benefits I see would be that:
- It would slightly reduce the amount of data written on the connection. If that's something we want to do, I think there are more fruitful approaches we could take (e.g. allowing compression on the wire).
- It would prevent the sender from needing to serialize and allocate memory for the entire JSON message ahead of time, and instead write it in chunks to the wire. However DAP messages are usually fairly small, and in many cases the work to write data to the connection multiple times would take longer than it would to allocate memory and write it in one go. Memory pooling techniques can also reduce the amount of allocations needed.

I don't think it's worth the trouble for questionable benefit.

**Comment by puremourning** [comment]
I agree with @connor4312

**Comment by weinand** [comment]
I fully agree with @connor4312

Since changing this is not an option, closing.
