### ISSUE TITLE
breakpoints not available on startup

### ISSUE THREAD

**Issue by maziac** [Microsoft/debug-adapter-protocol#17]
Hi,
I was trying to read the vscode.debug.breakpoints array from the launchRequest method.
But unfortunately the array is defined but empty even if breakpoints are set in the sources.

Additional info: If I access the same array from the restartRequest the array is filled with all breakpoints.

**Comment by weinand** [comment]
The issues in this repository are about the debug adapter protocol and not about any particular implementation of the protocol.
You are talking about some implementation problem of a frontend.
If this is correct and your frontend is VS Code, please file the issues against VS Code.
