### ISSUE TITLE
Add 'hasDataBreakpoint' attribute at VariablePresentationHint

### ISSUE THREAD

**Issue by isadorasophia** [microsoft/debug-adapter-protocol#173]
Currently, we can detect whether an object has a data breakpoint by checking for the "dataBreakpoint" kind from `VariablePresentationHint`.

However, the variable kind is generally used to identify the actual type of the object -- that is, if it's an interface, a method or a derived class. Data breakpoint tracking, which is generally used for UI purposes, should be declared as an attribute instead, since that can be set alongside other attributes and variable kinds.

```ts
interface VariablePresentationHint {
  /**
   * ...
   * 'dataBreakpoint': Deprecated: Indicates that a data breakpoint is
   * registered for the object. The 'hasDataBreakpoint' attribute should
   * generally be used instead.
   */
  kind?: 'property' | 'method' | 'class' | 'data' | 'event' | 'baseClass'
      | 'innerClass' | 'interface' | 'mostDerivedClass' | 'virtual'
      | 'dataBreakpoint' | string;

  /**
   * ...
   * 'hasDataBreakpoint': Indicates that the object has its value tracked by a
   * data breakpoint.
   */
  attributes?: ('static' | 'constant' | 'readOnly' | 'rawString' | 'hasObjectId'
      | 'canHaveObjectId' | 'hasSideEffects' | 'hasDataBreakpoint' | string)[];

  // ...
}
```

CC: @gregg-miskelly, @andrewcrawley, @weinand

**Comment by weinand** [comment]
This attribute "move" makes sense.
But please note that for backward compatibility we will not be able to remove the attribute from the "kind".

**Comment by isadorasophia** [comment]
Sure! That's why I suggested updating the documentation so we can point to "hasDataBreakpoint" instead.
