### ISSUE TITLE
Adding reference to the unity debugger extension

### ISSUE THREAD

**Issue by miniwolf** [Microsoft/debug-adapter-protocol#18]
https://github.com/Microsoft/vscode-debugadapter-node/wiki/VS-Code-Debug-Protocol-Implementations

I have joined the maintenance of the unity debugger extension: https://marketplace.visualstudio.com/items?itemName=Unity.unity-debug. Would it be possible to get me added to the name tags? I can see that @weinand was maintaining it.

Also the repository link can be added https://github.com/Unity-Technologies/vscode-unity-debug

**Comment by weinand** [comment]
@miniwolf please note that the debug adapter protocol now lives [here](https://microsoft.github.io/debug-adapter-protocol) and the DAP implementations [here](https://microsoft.github.io/debug-adapter-protocol/implementors/adapters/).

The "Debugger for Unity" and its repository is already on that list, but I've added your github id.
