### ISSUE TITLE
Restart request should have config argument to check if configuration changed

### ISSUE THREAD

**Issue by isidorn** [microsoft/debug-adapter-protocol#180]
Related VS Code issue https://github.com/microsoft/vscode/issues/118196

Today the spec of the DAP `restart` request doesn't say anything about changed launch configurations.
But we could add an optional `config` argument to the `restart` request so that an implementation has easy access to it and can compare it with the current values.

**Comment by weinand** [comment]
The `restart` request now takes an argument for the "launch" or "attach" configuration.
