### ISSUE TITLE
Module request/event/type clarification

### ISSUE THREAD

**Issue by Ev1lbl0w** [microsoft/debug-adapter-protocol#199]
I can't find any reliable information about [`Modules`](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Modules) request *(and subsequent [event](https://microsoft.github.io/debug-adapter-protocol/specification#Events_Module) and [type](https://microsoft.github.io/debug-adapter-protocol/specification#Types_Module))*: what are they, and in what scenarios are they used? Is it something related to a few specific programming languages and/or frameworks, or is it something applicable to every programming language/framework?

**Comment by fbrosseau** [comment]
Modules refer to the native concept of libraries being loaded into a process. In Windows terms, that's your .exe and all the .dlls that are used by the process. Other OSes all have similar equivalents. 

The point of this in the DAP is to show the list of _components_ loaded by your debuggee, along with various attributes (version, time of creation, etc etc) about each of them. This may or may not make sense in your particular DAP implementation/framework/language. 

[VSCode does not support the UI to show the loaded modules](https://github.com/microsoft/vscode/issues/110067), but if you target VisualStudio instead you can fully implement these parts of DAP, along with VS-specific semi-standard requests for manually loading the symbols of specific modules, as well as receive symbol loading preferences (do not attempt to load symbols by default for a given module, etc).

In fact you can look at that same link for a screenshot to get a general idea of what it looks like in VS.

**Comment by Ev1lbl0w** [comment]
Thank you so much!
