### ISSUE TITLE
A11y_Visual Studio Code Client_Sep2021_Debug Adapter Protocol_HomePage_ScreenReader: One of three , two of three.. Unnecessary announcement at footer section  in scan mode.

### ISSUE THREAD

**Issue by harshgangrade111** [microsoft/debug-adapter-protocol#207]
## **Actual:**

When navigate to text "Hello from Seattle and Zürich." narrator reads One of three , two of three.. Unnecessary announcement at footer section  in scan mode.

Same issue is also observed with Chrome+ NVDA.
**Same issue observed with throughout the application where similar footer present.**

## **Expected:**

Unnecessary position one of three, two of three should not be announce by screen reader in footer section "Hello from Seattle and Zürich." . It should directly announce link detail.

## **Environment Details:**

Application Name: Visual Studio Code Client
#URL: https://microsoft.github.io/debug-adapter-protocol
Browser Versions: Microsoft Edge Version 93.0.961.38 (Official build) (64-bit)
Chrome: Version 93.0.4577.63 (Official Build) (64-bit)
Windows Version: Windows10
Screenreader: Narrator, NVDA 2021.2

**Example Page UR**L: https://microsoft.github.io/debug-adapter-protocol

## **Repro Steps:**
1.	Open the URL: https://microsoft.github.io/debug-adapter-protocol
2.	Debug Adapter Protocol home screen will get open.
3.	Start Narrator and Press down arrow key to footer section at last then verify the issue.

## **User Impact:**

Screen reader Users will not get correct information.

## **Attachment:**
![#207](https://user-images.githubusercontent.com/60422426/133750188-06b829bc-8f39-439f-8934-6679ee00cbe4.gif)

“[Check out Accessibility Insights!](https://nam06.safelinks.protection.outlook.com/?url=https://accessibilityinsights.io/&data=02%7c01%7cv-stfe%40microsoft.com%7cb67b2c4b646d4f9561a208d6f4b5c39b%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c636965458850501301&sdata=mxhokIKNMb22llsjXHLgU3XZibj1Qfx37rpY4PU2sfE%3D&reserved=0) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

**GitHubTag:**#A11yTCS;#DesktopWeb;#Win10;#WCAG1.3.1;#STP;#FTP;#A11yMAS;#ChromiumEdge;#A11ySev2;#P2_Visual Studio Code Clien_Sep2021;#Narrator;#NVDA;#Visual Studio Code Client;#Chrome;#AILimited;#Element;ListItem;#P2_WCP;

**Comment by sana-ajani** [comment]
I don't think this is a bug, the items in the footer are a list, and the expected behavior is to read the number of items in the list.

**Comment by NiharikaTipirishetty** [comment]
#P2_debugadapterprotocol_Web_Sep2021;

**Comment by prabhudevu** [comment]
I verified issue in the Env: https://microsoft.github.io/debug-adapter-protocol, This is the Expected behavior with screen readers.Added Attachment for reference


![Screenshot (326)](https://user-images.githubusercontent.com/98821792/178405559-a4155958-49fa-4f00-ac58-493d79470e59.png)
![Screenshot (325)](https://user-images.githubusercontent.com/98821792/178405599-9694797a-28e4-4368-abbe-25ece63d0bc8.png)

**Comment by prabhudevu** [comment]
#closed;
