### ISSUE TITLE
New OutputEvent category for highly visible output messages

### ISSUE THREAD

**Issue by polinasok** [microsoft/debug-adapter-protocol#218]
According to the spec, there are now four categories:
```    category?: 'console' | 'stdout' | 'stderr' | 'telemetry' | string;```

I don't know how other editors treat these, but in vscode `console`, `stdout` and `stderr` all go to the same place (Debug Console). And they are usually used for target's output as well as continuous logging from the debugger or client. That stream of messages can be a lot to process and critical things can go unnoticed. It would be quite useful if there was an additional category that received special emphasis and could be used for extra critical one-off messages that really need to stand out and not get overlooked by the user. Additional context is here: https://github.com/microsoft/vscode/issues/111718.

**Comment by weinand** [comment]
I suggest to add a new value `important` to the Output event's `category` property.
(if you have suggestions for a better name, please let me know)

Its description text will explain that this is a "hint" for the client to make the message highly visible, e.g. by using a presentation style that makes it stand out from other output debug console messages or by showing a popup notification.
If a client does not understand `important`, the value 'console' is assumed.

Please note that this mechanism cannot be used to interakt with the user (e.g. ask for input).  

showing it as a non-modal popup

**Comment by weinand** [comment]
Since there was no opposition, I'll release the proposal.

**Comment by polinasok** [comment]
Thank you for addressing this. Sounds good.
