### ISSUE TITLE
Consider to use JSON RPC for a 2.0 version of the VS Code debug protocol

### ISSUE THREAD

**Issue by weinand** [microsoft/debug-adapter-protocol#226]
see https://github.com/Microsoft/vscode-debugadapter-node/issues/58 for details why JSON RPC hasn't been used from the beginning.

**Comment by jclsn** [comment]
So will you guys consider doing that after more than 6 years? 😁

**Comment by puremourning** [comment]
What's the point? This is a work creation scheme with almost zero actual benefit.

**Comment by jclsn** [comment]
@puremourning This is the point https://github.com/julia-vscode/julia-vscode/issues/3413

**Comment by puremourning** [comment]
I can't imagine how changing DAP to json rpc would fix that design. Every other debug adapter and client managed to implement DAP/v8 protocol. Not sure why it's impossible for Julia shrug.

**Comment by jclsn** [comment]
You know more about it than me. I was just trying to work my way through the issues I could find to see if there is a way to have this working in Vimspector :)

**Comment by connor4312** [comment]
At the moment we have no plans for a "2.0" for the debug adapter protocol; over the last 7 years, all changes made to DAP have been backwards-compatible. If there ever is a reason to move to a 2.0 protocol, we could consider this, but there are currently no plans for this.
