### ISSUE TITLE
Specify unsigned integers as in the range 0 to 2^31-1

### ISSUE THREAD

**Issue by michaelpj** [microsoft/debug-adapter-protocol#237]
Currently, some properties seem to be intended to be _unsigned_ integers, but have an upper bound of 2^31-1. This is atypical, since usually a 32-bit unsigned integer would have an upper bound of 2^32-1 instead, with 2^31-1 being the upper bound of a _signed_ integer.

This is awkward for implementations which would like to use a native unsigned integer type for these, but still have to deal with bounds issues since the bounds will not match what native unsigned 32-bit integers have.

These bounds in the DAP are apparently also preventing the LSP specification from using the more typical bounds for unsigned integers: https://github.com/microsoft/language-server-protocol/issues/1394#issuecomment-999008150

**Comment by KamasamaK** [comment]
I would not want this change. The compatibility issues it would introduce outweigh the awkwardness of some bounds checking.

Many languages do not have a native unsigned integer type and the current range allows the native signed integer type to be used in the implementation. This is the case for a Java library I help maintain. If the upper bound were increased, we would need to switch all of these implementation types to be signed 64-bit integers to accommodate.

**Comment by weinand** [comment]
no plans to change this.
