### ISSUE TITLE
Parsing logMessage templates

### ISSUE THREAD

**Issue by hoehrmann** [Microsoft/debug-adapter-protocol#24]
As of 4102c794ea44a36ec7153dfa3cc1609f1a0e792d the specification for `logMessage` is lacking in detail on how to parse the attribute

> If this attribute exists and is non-empty, the backend must not 'break' (stop) but log the message instead. Expressions within {} are interpolated.

For some languages it is quite normal for expressions to include the `{` and `}` delimiters, in Perl for instance you might want to log

```perl
Value of key field in hash is {$hash{key}} # ?
```

I would expect either `\`-escaping or actually configurable delimiters. For Perl it might be better to use backticks instead of curly braces, for instance, in which case the specification should allow implementations to vary on that point.

**Comment by hoehrmann** [comment]
I could also imagine that simply skipping over balanced nested curly braces would work to extract the "expressions", given that expressions here should be fairly simple. So if you parse the template and hit `{` you continue looking for `{` and matching `}`s up until you found the `}` that matches the outermost `{`. But that too should be noted, then.

**Comment by weinand** [comment]
@hoehrmann what exactly are you proposing to do here?
