### ISSUE TITLE
Add "lazy" property to the VariablePresentationHint

### ISSUE THREAD

**Issue by weinand** [microsoft/debug-adapter-protocol#246]
In https://github.com/microsoft/vscode/issues/134450 it was discussed how to support variables that are expensive/have side-effects and can be lazily evaluated.

Since DAP's `variable` request is inherently lazy, it is already possible to support lazy evaluation of expensive variables by introducing an intermediate `variable` with exactly one child. Expanding this variable in the client UI will trigger the "lazy evaluation" of the value by fetching the single child.

The only problem with this approach is that the intermediate `variable` makes the UI more noisy by introducing an additional node in the variables tree. To address this, we agreed to introduce a "presentation hint" on a variable that tells a client to render the variable in a way that reduces the noise.

So the proposal is to add an optional boolean flag `lazy` on the `VariablePresentationHint` type.

**Comment by puremourning** [comment]
But it's not a "presentation hint" though really is it? It's more like the "expensive" flag on the scope ?

Clients are free to ignore presentation hints I believe and if adapters start putting stuff in there that has material value (such as not causing side-effects), I think it should have more prominence.

WDYT?

**Comment by weinand** [comment]
@puremourning existing DAs are using the mechanism already without the "lazy" flag and without additional client support. See https://github.com/microsoft/vscode/issues/134450#issuecomment-971867869.
Introducing the "lazy" flag affects only the presentation and is optional.

**Comment by puremourning** [comment]
Oh I see. The suggestion is to _keep_ the additional `variable` in the hierarchy, but add a `hint` to say "this is a fake variable to save evaluating it". Got it. Thanks.
