### ISSUE TITLE
launch request type for listening/await modes

### ISSUE THREAD

**Issue by hoehrmann** [Microsoft/debug-adapter-protocol#25]
The `vscode-debug-perl` extension supports a `launch.json` configuration where it just starts a TCP server and awaits an incoming connection from a debugger (possibly on a remote machine). It neither launches the debugger nor the debuggee, so it's not really `request: launch`; it also does not attach to anything, so it's not `request: attach` either.

It also supports launching debugger+debuggee on the local machine. That matches `request: launch`, but it seems strange to use `request: launch` for both scenarios. Perhaps another type could be allowed, like `request: listen` (or `await`) to cover the first scenario?

**Comment by puremourning** [comment]
cpptools is the same. you use "launch" to attach to gdbserver for remote debugging. this paradigm seems common enough not to force all clients to change their protocol implementations. I don't see this as a big usability issue if the adapters document their options well enough

**Comment by weinand** [comment]
This is issue had already been raised by @felixbecker for the php-debugger some time ago.
But I agree with @puremourning that the benefit of a new "listening" request (in addition to "attach" and "launch") would be quite small.
If I would do the DAP again, I would actually merge "attach" and "launch" into a single request and completely leave it up to the DA to handle the differences.
