### ISSUE TITLE
How to verify breakpoints that are sent before launching the remote program?

### ISSUE THREAD

**Issue by NipunaRanasinghe** [microsoft/debug-adapter-protocol#251]
As per the debug adapter protocol, `setBreakpoints` request is allowed even before launching/attaching to a remote VM and therefore its not possible to verify the breakpoints (setting the `verified` attribute of the breakpoints to `true`) which were sent initially before the remote VM is spawn. 

Therefore, is there any possibility in the DA protocol to re-verify the initially sent breakpoints after connecting to the remove VM? @weinand WDYT?

**Comment by weinand** [comment]
@NipunaRanasinghe you said:

> setBreakpoints request is allowed even before launching

This is not true. The debug adapter is expected to send an `initialized` event to announce that it is ready to accept breakpoints. Please see section "Configuring breakpoint and exception behavior" in the [DAP overview](https://microsoft.github.io/debug-adapter-protocol/overview).

But if that doesn't work for you, your debug adapter can send `breakpoint` events to update the `verified` attribute later.

**Comment by NipunaRanasinghe** [comment]
@weinand Thanks for your inputs! `breakpoint` event does the trick :) its my bad that I missed that endpoint. Thanks for the help!
