### ISSUE TITLE
How to determine which Scope a variable belongs to ?

### ISSUE THREAD

**Issue by brianignacio5** [microsoft/debug-adapter-protocol#256]
On a `ScopeRequest` let's say it returns 2 scopes `Locals` and `Registers`. 

After a `VariableRequest` happens and the list of variables is returned to populate each scope with the variables.

The thing I don't understand is how to determine which variables belong to each Scope. Is there a way to determine this, and if so, could you provide a small example ?

**Comment by connor4312** [comment]
The `Scope` contains a `variablesReference`, which is given in a `VariableRequest` to retrieve those variables. Each scope will have a different `variablesReference`, and the ones belonging to each scope are the ones that returned when that reference is requested.

**Comment by brianignacio5** [comment]
Thank you very much, needed some detail about VariableRequest role with variablesReference.
