### ISSUE TITLE
[Question] How to handle inline breakpoints with SetBreakpoints request

### ISSUE THREAD

**Issue by gayanper** [microsoft/debug-adapter-protocol#268]
I started to look into DAP implementation for java to add support for java lambda debugging. But i couldn't find a separate request for inline breakpoints which can be added through vscode. such added breakpoints are received as line breakpoints into java DAP.
Can you provide me information how the DAP should handle/receive inline breakpoints ?

**Comment by gayanper** [comment]
Further looking at i see that we have `column` in the SourceBreakpoint type. Is this is supposed to use for inline breakpoints ? Because when i looked at the json payload from vscode i see that i receive the column i added the inline breakpoint ?

**Comment by connor4312** [comment]
Let us know if you have any additional questions 🙂
