### ISSUE TITLE
Support completion for condition in Conditional Breakpoint

### ISSUE THREAD

**Issue by apupier** [microsoft/debug-adapter-protocol#269]
it would be nice to be able to provide completion for condition attribute of a Conditional breakpoint

For instance, to leverage it in VS Code at this place:
![Screenshot from 2022-05-16 13-58-35](https://user-images.githubusercontent.com/1105127/168587849-dbba6ccd-83ae-4070-a882-1f79900bca43.png)

**Comment by connor4312** [comment]
Yes, I think this should be a feature of the client (e.g. by integration in LSP) rather than the debugger.

If the debugger is running _and_ (for js) paused in the same scope, then we could provide additional information about variables. But the language server should be able to do a better job in general.

**Comment by weinand** [comment]
@apupier please note that neither VS Code nor DAP knows anything about the **Language Server Protocol**. So adding support in LSP does not help VS Code or debug extensions to implement "completion support for breakpoint conditions" generically. The first thing we need is a feature request for VS Code (if there is not already one). Then VS Code needs to check whether the existing language API `CompletionItemProvider` is sufficient. If it is not, then a new language API must be defined. And if we have this in hand we can try to implement this based on existing LSP features or a new feature.

**Comment by connor4312** [comment]
I'll go ahead and close this as it sounds like we have consensus that DAP isn't the place for this feature.

If there is disagreement or more discussion, we can reopen it 🙂
