### ISSUE TITLE
Reinserting breakpoints in 'eval' code after restarting the debugged application

### ISSUE THREAD

**Issue by zherczeg** [microsoft/debug-adapter-protocol#273]
I am working on a debug adapter for a JS engine. When an `eval()` call is executed, my adapter assigns a `sourceReference` to its source code, and VSCode gets this code using a `SourceRequest`. Breakpoints, etc. work.

However, when I restart the JS engine, the active breakpoints are not inserted in eval codes, even though my adapter can find them using MD5 checksums. It seems there are two independent source codes in VSCode after the restart, one for the previous run *with* breakpoints, and another *without* breakpoints.

Is it possible to tell vscode that these sources are the same and it should use (insert) the existing breakpoints (similar to regular files).

Another question: I send an `InitializedEvent` after a new script is loaded by the JS engine which triggers the update breakpoint event. Since only one file is loaded, this seems unnecessary (gives a lot of work for vscode), but I couldn't find a better solution. Is there any?

Thank you for the help

**Comment by zherczeg** [comment]
Thank you for the help!

> If you want to update a [breakpoint](https://microsoft.github.io/debug-adapter-protocol/specification#Events_Breakpoint)'s state, you can use the breakpoint event.

So I need to record all breakpoints for files not loaded yet (not known by the engine), and "update" them when the file is known?

**Comment by connor4312** [comment]
> So I need to record all breakpoints for files not loaded yet (not known by the engine), and "update" them when the file is known?

Yep

**Comment by connor4312** [comment]
Let us know if you have any additional questions 🙂

**Comment by zherczeg** [comment]
Thank you for the help! Breakpoints are working better now.
