### ISSUE TITLE
Clarify what seq means for response and event

### ISSUE THREAD

**Issue by rillig** [microsoft/debug-adapter-protocol#275]
The field `ProtocolMessage.seq` is mandatory for all kinds of protocol messages.
The documentation says what it means when used in a request.
There should be similar documentation on what its purpose is for responses and events.
The documentation should make it obvious why this is a mandatoy field.
If the field were optional, it could save a bit of bandwidth.

**Comment by weinand** [comment]
The `seq` field is declared in `ProtocolMessage` and then inherited by `Request`, `Event`, and `Response`, I don't think that there is a need to repeat the documentation of `seq` in subclasses.

But I will improve the documentation of `ProtocolMessage.seq` to make it more obvious why it is essential for the implementation of the DAP protocol.
