### ISSUE TITLE
Be consistent about redundant documentation

### ISSUE THREAD

**Issue by rillig** [microsoft/debug-adapter-protocol#280]
> Mandatory (short) title of the progress reporting

> Optional, more detailed progress message

Some properties are documented as mandatory or optional, other properties aren't.
The specification should consistently omit this information, as it is already expressed by the data type.

**Comment by connor4312** [comment]
I'm always a fan of having a single point of truth, so I would be in favor of removing the redundant docs since they're expressed by the type (and/or can be added in an automated way to docs on the generated types.)

Thoughts @weinand @roblourens?

**Comment by roblourens** [comment]
I agree
