### ISSUE TITLE
Consistently use or do not use the word 'must'

### ISSUE THREAD

**Issue by rillig** [microsoft/debug-adapter-protocol#283]
> The value true (or a missing property) signals …

> The value false must be returned …

As these sentences are intended to have the same structure, they should use the same grammar.
Either both should use 'must' or neither of them.

**Comment by weinand** [comment]
I've eliminated only those occurrences of "must" that  match the described pattern from [above](https://github.com/microsoft/debug-adapter-protocol/issues/283#issue-1268656384).
