### ISSUE TITLE
Use type system for modeling Source.properties.origin.description

### ISSUE THREAD

**Issue by rillig** [microsoft/debug-adapter-protocol#288]
The documentation of Source.properties.origin.description says:
> The (optional) origin of this source: possible values 'internal module', 'inlined content from source map', etc.

Elsewhere in the specification, constraints like these are modeled via the type system.
For consistency, this case should be modeled using an `_enum` type as well.

**Comment by connor4312** [comment]
The list of origins is non-exhastive, and is up to the Debug Adapter to provide. For example, source maps are things that only exist in JavaScript, so it's not something we would specify as a restricted enum in DAP. I will adjust the wording to make this clearer.

**Comment by rillig** [comment]
> The list of origins is non-exhastive

That's why I suggested `_enum` as the type, and not the restricted `enum`.

> it's not something we would specify as a restricted enum in DAP.

I prefer to have an _extensible_ enum here, like it is already done elsewhere in the specification, that predefines a few values for use cases that are already known, to provide a guideline to the implementors, and documents the remaining values as implementation-defined.
