### ISSUE TITLE
Clarify representation of ChecksumAlgorithm

### ISSUE THREAD

**Issue by rillig** [microsoft/debug-adapter-protocol#291]
* Is `MD5` represented as hex string?
* Is `SHA1` represented as hex string?
* Is `SHA256` represented as hex string?
* Is `timestamp` represented as milliseconds, seconds, ISO 8601, RFC 822?

What about other checksum algorithms?

**Comment by gregg-miskelly** [comment]
MD5/SHA1/SHA256 hashes should all be hex strings.

Example: `{"algorithm":"SHA256","checksum":"b7bd461fc5ba9e1278eed89e11158fbc09b966f23102a1b746b5883bb1f15625"}`

**Comment by gregg-miskelly** [comment]
@weinand I am happy to send a PR for MD5/SHA1/SHA256.

Are you aware of anyone using `timestamp`? I only see a vague reference to it in https://github.com/microsoft/vscode-debugadapter-node/issues/63.

If we don't know of anyone using it, does anyone have a preference between leaving it unspecified (in case someone is actually using it) vs just picking something?

CC @andrewcrawley

**Comment by andrewcrawley** [comment]
I'm not aware of anyone using `timestamp` - we certainly don't.  My original intent in proposing it was just to show that other checksum types besides hashes were possible.

**Comment by connor4312** [comment]
I've made a PR here: https://github.com/microsoft/debug-adapter-protocol/pull/299
