### ISSUE TITLE
What is the current release version?

### ISSUE THREAD

**Issue by jonahgraham** [microsoft/debug-adapter-protocol#331]
At the moment https://microsoft.github.io/debug-adapter-protocol/ shows 1.57.0 as latest version:

![image](https://user-images.githubusercontent.com/679236/189417984-f56fd923-b5b4-4f09-8c02-610a2264df1c.png)

but the change history shows 1.58.0: https://microsoft.github.io/debug-adapter-protocol/changelog

Is #326 which is listed as part of 1.59.x officially released yet? We want to start using it (xref https://github.com/eclipse/lsp4j/issues/662)

Thanks!

**Comment by weinand** [comment]
Yes, #326 is part of 1.59.x which will be released at the end of September.
If you want to use it earlier, you can just use the schema and doc of DAP's "main" branch.

**Comment by jonahgraham** [comment]
Thanks @weinand. The website lists 1.57 as current version. I assume it should say 1.58. See screenshot above.
