### ISSUE TITLE
Request to copy variables to another frame 

### ISSUE THREAD

**Issue by brichet** [microsoft/debug-adapter-protocol#360]
Is there a specification allowing copying complex variables from a frame to another ?

The only way I have found to copy a variable from local frame to global frame is to use a `setExpression` request, which works only for 'string-able'  types.
See https://github.com/jupyterlab/jupyterlab/pull/13476 for reference.

May it be interesting to add such a specification to the DAP ?

**Comment by roblourens** [comment]
I don't really understand what you mean, from one frame to another, or "complex". This doesn't sound like a generic operation that would make sense for different languages, runtimes, etc.

**Comment by brichet** [comment]
Thanks @roblourens for the answer.

Maybe I misunderstood the way frames and scopes work.

Using *Python* and *debugpy*, if I set a breakpoint in a function, I will get 2 frames (*module* and *function*), each one having 2 scopes (*global* and *local*).

The idea is to be able to copy a variable from the *local* scope of the *function* frame to the *global* scope of the *module* frame, to be able to inspect that variable after the debug session.
Since https://github.com/microsoft/debugpy/pull/1147 we can use the `globals()` keyword in `setExpression`, which does it for Python / debugpy in that very specific case.

But it can be more generic, allowing to copy a variable from a scope of a frame to another scope of another frame.

For `Jupyter` project, the UI provides a debugger tools that should be able to use any debugger using DAP. This feature can be implemented at (1) kernel level (see https://github.com/ipython/ipykernel/pull/1055 or https://github.com/jupyter-xeus/xeus-python/pull/562) or at (2) debugger level. 
For the first option, it should be ported on all kernels of all languages.
For the second option, the feature should be specified in DAP to be generic and provided natively by the debuggers.

But maybe there is a simpler solution that I missed.

**Comment by roblourens** [comment]
This is interesting, but I doubt that it is generally relevant to other languages or IDEs enough for it to make sense in DAP. I think it would make more sense to handle it the way you already do with `setExpression` per language.
