### ISSUE TITLE
Enable error notifications via OutputEvent

### ISSUE THREAD

**Issue by corneliusweig** [microsoft/debug-adapter-protocol#369]
The DAP output event has the category `"important"`, which creates a popup in VSCode with the `"warning"` severity (https://github.com/microsoft/vscode/blob/da0309f2514ac22ac82dcd080cfc764fe2a1f434/src/vs/workbench/contrib/debug/browser/debugSession.ts#L1101). My understanding of the API is that the OutputEvent should not specify the severity directly, hence the categories `"console"`, `"important"`, etc.

The drawback is that debuggers cannot control the severity level of the notification. In particular, it is not possible to show error-style notifications in VS Code.

Therefore, I propose to add an additional category `"critical"`, which is similar to, but more severe than `"important"`. In particular, the `"critical"` category should show a popup with the `ERROR` category.

**Comment by roblourens** [comment]
Can you give an example of the kind of error you want to show that doesn't fit into existing ways to return an error response?

I'm actually not a big fan of the `"important"` category. I don't really like some of the usages of it, and the user doesn't have any control over these (no "don't show again" option like many other notifications in vscode). And we've had the issue that this message doesn't show up in the debug console, for example.

**Comment by corneliusweig** [comment]
Some examples I'm looking to clearly mark as fatal errors are:

- when the debugger needs an additional dependency, which is not installed. The debugger cannot recover from this condition without user interaction.
- when startup failed because the binary could not be built
- when communication with the debugged binary failed

I agree that the `"important"` category is a bit strange, because it controls different dimensions at the same time (severity and whether to show as notification). However, the alternative to give more control to the DAP layer how a message is shown, feels too verbose.

**Comment by puremourning** [comment]
IMO all of the above should should result in the `initialise`/`launch` or `attach` requests failing with an appropriate error message, rather than using 'output' events. Clients will surface a request failure, particularly for these requests, prominently because it's important feedback for why the basic operation (continue, attach, whatever) isn't working. Other adapters do this.

The output/console is actually not the right place for that; it's a failure of some action (start debugging, continue, whatever), not some unsolicited message in the console.

**Comment by roblourens** [comment]
I agree with that, seems these should just be failures to handle a DAP request from the client

**Comment by corneliusweig** [comment]
Thanks for the feedback. I think this should work for the cases I had in mind. If not, I'll reopen the issue.

Thanks again!
