### ISSUE TITLE
Debugger: Function Names not Visible in the Call Stack View

### ISSUE THREAD

**Issue by walles** [microsoft/debug-adapter-protocol#383]
When I'm debugging Go code and looking at the call stack I have two options:
* Have the side bar as wide as I'd like (good!) and don't see any function names in the stack trace (bad)
* See function names (good!) but have the side bar covering a third of my screen (bad)

I would prefer if function names were visible in the call stack view without having to make the side bar really really wide.

The space is there, this is just about prioritizing what to show.

# Demo

https://user-images.githubusercontent.com/158201/229415502-941c4bee-cc7f-4190-8599-58c9f538e08a.mov

**Comment by walles** [comment]
Wrong project, sorry for the noise :(.

**Comment by bew** [comment]
> Wrong project, sorry for the noise :(.

What is the correct project? Go's  DAP ?

**Comment by walles** [comment]
TBH I'm not 100% sure, but I did report it here instead: https://github.com/microsoft/vscode/issues/178964

I think this is an UI issue (belonging in the main VSCode project) rather than a debugger-protocol issue (belonging here).

But if you disagree I'm ready to be corrected, as I said I'm not 100% sure where this should go.
