### ISSUE TITLE
How should clients handle `showUser=false` but `url` given?

### ISSUE THREAD

**Issue by rehmsen** [microsoft/debug-adapter-protocol#387]
# Spec:
https://github.com/microsoft/debug-adapter-protocol/blob/4900b7efce3495a29d8b97d71c0fe3a6cdb6f28a/debugAdapterProtocol.json#L3286-L3297

# Issue

It is not very clear how clients should handle messages that have `showUser=false` but a URL given. For example, VSCode ignores `showUser` when a URL is given and shows a dialog regardless:
https://github.com/microsoft/vscode/blob/c29e4b0fdb6b63c23be7055feb5a188784a86691/src/vs/workbench/contrib/debug/browser/rawDebugSession.ts#L771-L776

**Comment by roblourens** [comment]
I think it should be interpreted the way you expect- it should determine whether the error is shown to the user. I think there are bugs in vscode's implementation that are causing confusion. Let's continue in https://github.com/microsoft/vscode/issues/180488
