### ISSUE TITLE
Lifetime of DataBreakpoint.dataId not specified

### ISSUE THREAD

**Issue by tromey** [microsoft/debug-adapter-protocol#390]
I noticed that the lifetime of the `DataBreakpoint.dataId` values is not specified.  In my implementation (I work on an implementation of the protocol built in to GDB) it would be convenient for these to only live until the next `continue`, like variables.  However the "Lifetime of Objects References" section does not mention this particular ID and I don't think it's entirely clear.

One way to improve this would be to update ID in the specification to note its expected lifetime.

**Comment by connor4312** [comment]
I believe the correct answer is to say it lives as long as the data referenced in the `dataBreakpointInfo` request lives. That is, if only the minimum `name` is given, it is expected to live indefinitely. If a `variablesReference` and/or `frameId` is given, it's expected to live as long as those IDs/references remain valid.

Thoughts @roblourens?

**Comment by roblourens** [comment]
I agree with that but I don't see a `frameId` involved? But basically the dataId is derived from `DataBreakpointInfoArguments` and so its lifecycle should match the lifecycle of whatever was given in there.

**Comment by tromey** [comment]
> I agree with that but I don't see a `frameId` involved? But basically the dataId is derived from `DataBreakpointInfoArguments` and so its lifecycle should match the lifecycle of whatever was given in there.

There's a `frameId` in `DataBreakpointInfoArguments`, but also (perhaps) the variable references have implied lifetimes.  Anyway my wish here is that the spec could be explicit about precisely how long different identifiers are expected to survive.

**Comment by connor4312** [comment]
Proposed wording:

> An identifier for the data on which a data breakpoint can be registered with the `setDataBreakpoints` request or null if no data breakpoint is available. If a `variablesReference` or `frameId` is passed, the `dataId` is valid in the current suspended data, otherwise it's valid indefinitely. See 'Lifetime of Object References' in the Overview section for details. The validity breakpoints set using the `dataId` in the `setDataBreakpoints` request may outlive the lifetime of the associated `dataId`.
