### ISSUE TITLE
ExceptionFilterOptions does not have hitCondition

### ISSUE THREAD

**Issue by tromey** [microsoft/debug-adapter-protocol#396]
`SetExceptionBreakpointsResponse` says:

> [...] and whether the condition or hit count expressions are valid

However, `ExceptionFilterOptions` only mentions `condition`, not `hitCondition`.

Since all other breakpoints have `hitCondition`, I think adding it to exceptions would be best.

**Comment by connor4312** [comment]
So far there hasn't been apparent desire for hit conditions in breakpoints. I will remove the extraneous wording for now, but we can always revisit this later on.
