### ISSUE TITLE
Valid values for IDs are underspecified

### ISSUE THREAD

**Issue by int19h** [microsoft/debug-adapter-protocol#40]
The spec just says that all IDs are `number`s - which is to say, 64-bit floats. It does not say much about how they should be compared, including weird cases like `NaN` or positive/negative zero, which are seemingly legal.

In practice it seems that protocol clients have much more stringent limitations - for example, VS uses 32-bit integers internally for many IDs, and is unable to cope with any number that doesn't fit. It would be nice to reflect it in the spec itself, limiting the values to some sane subset that all current implementations support in practice (e.g. `int32 > 0`?).

**Comment by vadimcn** [comment]
DAP schema types all IDs as integers, so, clearly, they cannot use be fractional numbers.  Since VSCode is implemented in javascript, I think the largest integer it can handle is 2<sup>53</sup> - 1.

**Comment by weinand** [comment]
see #90
