### ISSUE TITLE
"Object ID" is not defined

### ISSUE THREAD

**Issue by tromey** [microsoft/debug-adapter-protocol#412]
The specification for `VariablePresentationHint` mentions "Object ID" in two places in the text for the `attributes` field.  However, this term isn't defined or used anywhere else.

**Comment by gregg-miskelly** [comment]
Full Visual Studio has an extension to DAP to allow creating an 'object id', which is using for .NET debugging (though in theory it could make sense for other languages with a compacting garbage collector), which is what these refer to.

`hasObjectId` and `canHaveObjectId` should have really stayed in this same extension, but it looks like they mistakenly leaked into here. At this point I think we should probably just clarify the documentation to indicate these are Visual Studio only so we don't break any generator that might get upset if we removed them, though we could certainly also just remove them.

**Comment by connor4312** [comment]
Removing them would cause compatibility issues for generated clients who might use them. I will just make a note of that usage in the spec.
