### ISSUE TITLE
Policy for recording changes in changelog

### ISSUE THREAD

**Issue by sztomi** [microsoft/debug-adapter-protocol#418]
The `notStopped` enum value for `Response::message` was added in this (apparently unrelated) commit: https://github.com/microsoft/debug-adapter-protocol/commit/3873fd487b3c5d0d0a5beb7c62bdbe83859d753e

And it's not called out in the changelog. Is there currently a policy that defines what should go into the changelog? Could there be other hidden changes like this, or this is a rare exception? (note, this is not meant to be thinly veiled complaint, I'm genuinely interested as a maintainer of an implementation).

**Comment by connor4312** [comment]
It was a mistake to not add that to the changelog, I'll open a PR to retroactively add it.
