### ISSUE TITLE
Tag specification versions

### ISSUE THREAD

**Issue by sztomi** [microsoft/debug-adapter-protocol#420]
As a maintainer of an implementation, I'd like a way to clearly indicate what version my current implementation conforms to. Version numbers are listed in the changelog, but the corresponding point in history is difficult to find without any tags in the repository. Tags/releases would also make it possible to auto-generate the changelog on Github, eliminating human error such as https://github.com/microsoft/debug-adapter-protocol/issues/418.

**Comment by connor4312** [comment]
I've pushed tags for all versions since 1.32 when we started recording a normal changelog
