### ISSUE TITLE
Add a `reason` for why breakpoints are not verified

### ISSUE THREAD

**Issue by DanTup** [microsoft/debug-adapter-protocol#425]
In Dart, we initially response to `setBreakpoints` with `verified:false`. When the VM resolves the breakpoint locations, we send a breakpoint update with `verified:true` and the resolved location. This usually only happens just before the code first runs (libraries are lazily loaded).

The nvim-dap client treats `verified:false` as invalid, warning "Server rejected breakpoint":

https://github.com/mfussenegger/nvim-dap/blob/1c63f37f95cd4fb54512898168138d9a75d1516a/lua/dap/session.lua#L887-L888

My feeling was that Dart was doing the right thing (it seemed to work well in VS Code, breakpoints being greyed until their locations resolved), but re-reading the spec I'm less sure:

> The `verified` property of a `Breakpoint` object signals whether the exception breakpoint or filter could be successfully created and whether the condition is valid. In case of an error the `message` property explains the problem. The `id` property can be used to introduce a unique ID for the exception breakpoint or filter so that it can be updated subsequently by sending breakpoint events.

"could be successfully created" makes it seem like it's used for failure, but it also probably doesn't make sense to update a breakpoint later if it failed. Could this be clarified in the spec? Is using `verified:false` temporarily until the location is resolved a valid use, or should we send `verified:false` and just update the location (if required) later?

**Comment by connor4312** [comment]
>  Is using verified:false temporarily until the location is resolved a valid use

Yea, it is. I think your behavior is pretty common and nvim-dap may want to update their verbiage. Alternatively Dart could provide a message stating something like "Code not yet loaded".

**Comment by DanTup** [comment]
Confusion about unverified breakpoints has come up a few times since we started using `verified` in this way (for ex. https://github.com/Dart-Code/Dart-Code/issues/4734). Users are used to always seeing red breakpoints (when we didn't support lazy-resolving them) and now see grey breakpoints and think they're broken.

The spec also has wording that suggests `verified: false` means they _failed_ to verify rather than they might not _yet_ be verified:

```
   * This is shown to the user and can be used to explain why a breakpoint could
   * not be verified.
```

I feel like there might be value in having "not yet verified" as a first-class state, allowing editors to distinguish between:

- not yet verified (grey)
- verified (red)
- failed to verify (error `!`?)

We can certainly add "Breakpoint not yet verified" to the tooltip (in `message`), but I think making the difference between failures and lazy-verified breakpoints would be much better.

**Comment by connor4312** [comment]
This could be done with the addition of an optional `reason` on the Breakpoint.

**Comment by DanTup** [comment]
@connor4312 that sounds reasonable to me. Should I file a separate issue, or should we tweak this one to be for that (I think adding the reason would address this issue by making it clearer that this is a valid use).

I've had a number of issues raised recently around confusion about grey breakpoints because we only recently started resolving them correctly. I don't want to revert that change (because I think it provides useful information for breakpoints in invalid locations), but I do think the current behaviour (particularly when people are so used to red breakpoints always) is pretty confusing.

**Comment by connor4312** [comment]
Let's tweak this issue to support that. I propose the addition of a property, with some initial minimal states. I don't think we need a verified `reason`, it doesn't add any extra information.

```
interface Breakpoint {
  /**
   * A machine-readable explanation of why a breakpoint may not be verified.
   * If a breakpoint is verified or a specific reason is not known, the adapter
   * should omit this property. Possible values include:
   * 
   *  - `pending`: Indicates a breakpoint might be verified in the future, but
   *    the adapter cannot verify it in the current state. 
   *  - `failed`: Indicates a breakpoint was not able to be verified, and the
   *    adapter does not believe it can be verified without intervention.
   */
  reason?: 'pending' | 'failed';
```

**Comment by DanTup** [comment]
That looks good to me :-)

**Comment by roblourens** [comment]
> and the
>   *    adapter does not believe it can be verified without intervention.

Can the adapter really know this? Isn't it possible in most runtimes that a new module could be loaded at any moment where this breakpoint can be bound?

**Comment by DanTup** [comment]
> Can the adapter really know this? Isn't it possible in most runtimes that a new module could be loaded at any moment where this breakpoint can be bound?

If "most" runtimes allow this but not "all", wouldn't that suggest some could?

I don't know the reason but the spec already has this:

```ts
  /**
   * A message about the state of the breakpoint.
   * This is shown to the user and can be used to explain why a breakpoint could
   * not be verified.
   */
  message?: string;
```

However this is just a `string` so clients can't use it to visually distinguish between reasons. If every unverified breakpoint actually means "not verified yet", then I wonder why `message` existed in the first place?

**Comment by roblourens** [comment]
> If "most" runtimes allow this but not "all", wouldn't that suggest some could?

Can the Dart debugger accurately know when all files are loaded, and are new files not allowed to be dynamically loaded later?

**Comment by DanTup** [comment]
> Can the Dart debugger accurately know when all files are loaded, and are new files not allowed to be dynamically loaded later?

I don't think so. Although @connor4312 gave some examples above of cases where breakpoints might be "definitely invalid" versus "not yet resolved". I think users should be able to tell in VS Code the difference between a "breakpoint that is not going to work" and a "breakpoint that is not yet resolved because this script isn't compiled".

**Comment by roblourens** [comment]
> parse errors in the breakpoint expression

This makes sense to me, and invalid log messages, and also maybe there are times when the DA knows that the requested location will never be valid. I'm fine with the proposal
