### ISSUE TITLE
Clarify what it means if "kind" is omitted in "runInTerminal" request

### ISSUE THREAD

**Issue by weinand** [microsoft/debug-adapter-protocol#43]
See https://github.com/Microsoft/vscode/issues/71844

**Comment by rogalmic** [comment]
Hi,

Is there any update for this one?

**Comment by weinand** [comment]
It was an oversight to leave the `kind` property optional in the spec.

Since making `kind` mandatory in the spec would be breaking, I suggest that we just document what a missing `kind` attribute means: a missing `kind` property defaults to `"kind": "integrated"`.
