### ISSUE TITLE
Lifetime of variableReference after setVariable

### ISSUE THREAD

**Issue by tromey** [microsoft/debug-adapter-protocol#438]
While implementing `setVariable` for gdb, I came across a strange scenario.

Suppose there is some variable that has structure, so it has reported a non-zero `variableReference`.  Next, the client changes the value of this variable by sending `setVariable` request (using the variable's parent and the variable's name).  However, the new value does not have any children -- so it would report `variableReference` as `0`.  (This scenario can happen, e.g., in Rust debugging, where some variants of an `enum` may hold a value and some may not.)

In this situation, the original `variableReference` of the changed variable is no longer valid.  However, nothing in the specification actually says this.

If any children of the variable were fetched, they may also have been assigned a non-zero `variableReference`, which are now invalid.  This sort of thing can also happen if an assignment removes elements from a vector.

**Comment by connor4312** [comment]
I agree, we should clarify:

```ts
interface SetVariableResponse extends Response {
  body: {
    // ...

    /**
     * If `variablesReference` is > 0, the new value is structured and its
     * children can be retrieved by passing `variablesReference` to the
     * `variables` request as long as execution remains suspended. See 'Lifetime
     * of Object References' in the Overview section for details.
     * 
     * If this property is included in the response, the `variablesReference`
     * passed in the `SetVariableArguments`, and those of
     * its children, are no longer valid.
     */
    variablesReference?: number;
```

**Comment by tromey** [comment]
```
     * If this property is included in the response, the `variablesReference`
     * passed in the `SetVariableArguments`, and those of
     * its children, are no longer valid.
```
I think this part is slightly incorrect, in that the `variablesReference` passed to `setVariable` would still be valid -- it indicates the parent container of the variable to be set.  The variable itself is chosen by `name`.

**Comment by connor4312** [comment]
oop, good catch, fixed
