### ISSUE TITLE
Clarify meaning of "system process"

### ISSUE THREAD

**Issue by tromey** [microsoft/debug-adapter-protocol#439]
The "Process Event" docs say:
```
     * The system process id of the debugged process. This property is missing
     * for non-system processes.
```
However, they don't explain what a "system process" might be.  Consequently, I don't know when gdb should or should not emit this field.

**Comment by connor4312** [comment]
I don't have the historical context behind this property -- @gregg-miskelly or @roblourens perhaps?

**Comment by roblourens** [comment]
Oh, I have no idea. VS Code doesn't use it. It kind of sounds like it could be a PID and a "non-system process" would be a process that doesn't represent a real OS process but I don't know what that use-case would be. @isidorn?

**Comment by roblourens** [comment]
VS Code doesn't look at ProcessEvent at all

**Comment by gregg-miskelly** [comment]
It means the operating system's process id (as opposed to some internal id from the debugger).

**Comment by gregg-miskelly** [comment]
And a 'non-system process' is trying to talk about some sort of virtual process. Examples: coredump, in-memory snapshot of a process's state, process that represents some sort of remote device, etc.

**Comment by connor4312** [comment]
Appreciate the clarification 🙂  DAP doesn't have "process IDs", so I assume this was a forward-looking change in the event that we ever add internal IDs for processes.

My clarification wording feels a little clumsy, happy for any suggestions:

```ts
interface ProcessEvent extends Event {
  event: 'process';

  body: {
    /**
     * The process ID of the debugged process, as assigned by the operating
     * system. This property should be omitted for logical processes that do 
     * not map to physical processes on the machine.
     */
    systemProcessId?: number;
```

**Comment by gregg-miskelly** [comment]
> so I assume this was a forward-looking change in the event that we ever add internal IDs for processes.

No, some debuggers have internal ids for processes, even if they aren't exposed in DAP. The intent was to say "we don't care about your internal ids, please don't send them" :)
