### ISSUE TITLE
Debug session recovery in the case of brief disconnection 

### ISSUE THREAD

**Issue by PavelSosin** [microsoft/debug-adapter-protocol#44]
Actual:
It looks like DAP inherits single node architecture where application and debugger are located on same computer or local network, both are state-full and restart of both partners can be manually synchronized. in the real world cloud scenario the debugger client are stateful but everything between is stateless

**Comment by weinand** [comment]
Since DAP is a protocol between a debugger UI and an abstract debugger, it doesn't make any assumptions about where the "application" (aka "debug target") is running.

**Comment by PavelSosin** [comment]
Agree. Debugging server should be able to detect application application crash and DAP protocol already has corresponding notification. How to handle communication errors or debugging server crash is described in infrastructure documentation. What infrastructure expects from client and what client can expect from infrastructure is not defined by the high level protocol.
