### ISSUE TITLE
Example on how to launch debug adapter

### ISSUE THREAD

**Issue by GniLudio** [microsoft/debug-adapter-protocol#440]
Where can I find simple examples on how to launch a debug adapter?

I want to understand what the required steps for an editor are to support the debug adapter protocol,
but I can only find packages for visual studio code which implement a debug adapter.
(without explanations how other editors can use them)

Additional information:
* Examples written in C# would be nice. (since my program/editor is written in C#)
* I want to start/test with a single language, starting with C#, Python or Lua.

**Comment by connor4312** [comment]
This depends on your client/editor, and the adapter you want to use. Many adapters support starting a server on a port or pipe over which the [protocol](https://microsoft.github.io/debug-adapter-protocol/overview#debug-session-start) is spoken.

> When a debug session starts, the development tool needs a way to communicate with the debug adapter that implements the Debug Adapter Protocol. How the debug adapter comes to life is not part of the protocol specification

**Comment by GniLudio** [comment]
@connor4312 And where can I find examples?

**Comment by connor4312** [comment]
It depends on your client/editor, and the adapter you want to use. It's the prerogative of the client to design a system to load and interact with adapters. VS Code, in its marketplace and extension system, has [one way](https://code.visualstudio.com/api/extension-guides/debugger-extension) to do this. Neovim, to give a random example, [has another](https://github.com/mfussenegger/nvim-dap).
