### ISSUE TITLE
Evaluation time out

### ISSUE THREAD

**Issue by KaivnD** [microsoft/debug-adapter-protocol#446]
I make a EvaluateRequest, which probably take so much time and reached request timeout. Is this timeout configurable?
And this is my code
```ts
    const {result} = await session.customRequest("evaluate", {
      expression:  `<expression takes long time>`,
      frameId: currentFrameId,
      context: "clipboard",
    });
   // result here is just a string `Evaluation time out`
```

**Comment by connor4312** [comment]
DAP doesn't include any specification for timeouts. That sounds like behavior exhibited by the adapter in question, which they may allow you to configure.
