### ISSUE TITLE
Clarifications for setExceptionBreakpoints

### ISSUE THREAD

**Issue by tromey** [microsoft/debug-adapter-protocol#449]
While working on the gdb implementation of `setExceptionBreakpoints`, I had some questions I couldn't resolve from the spec.

I assume that `exceptionOptions` is a parallel array to `filters` and `filterOptions`.  That is, I think gdb should concatenate `filters` and `filterOptions` and then expect `exceptionOptions` to have the same length as this combined array. 

If that's correct, I suggest spelling it out in the text, and also removing the mention of `exceptionOptions` from:

> The Breakpoint objects are in the same order as the elements of the filters, filterOptions, exceptionOptions arrays given as arguments

Also it would be good to say what should happen if this array is not sized properly.

If this isn't correct, it would be good to know how this is really supposed to work.

Guidance about the meaning of `ExceptionPathSegment` would also be good.  For example, gdb can catch C++ or Ada exceptions.  Is a path segment intended to match the namespace structure of a C++ class name?  Or ... well, I couldn't think of what else it might mean.

**Comment by tromey** [comment]
I forgot to mention -- I couldn't understand when `breakMode` == `never` would be useful.

**Comment by connor4312** [comment]
> Guidance about the meaning of ExceptionPathSegment would also be good. For example, gdb can catch C++ or Ada exceptions. Is a path segment intended to match the namespace structure of a C++ class name?

Sure. What the path segment means is up to the DA. It's not used in VS Code, but VS uses it to implement a UI like so

![image](https://github.com/microsoft/debug-adapter-protocol/assets/2230985/b390dc1f-9384-4303-89d9-c9ac31cd15c8)

"never" is used to indicate that a DA should never break on exceptions at the given path. 

> I assume that exceptionOptions is a parallel array to filters and filterOptions. That is, I think gdb should concatenate filters and filterOptions and then expect exceptionOptions to have the same length as this combined array.

This is not correct; the exceptionOptions is another array that specifies break behavior. Some clients/DAs always send and empty `filters` array and only send exceptionOptions.

I'll open a PR with some clarifications.

**Comment by tromey** [comment]
Thanks for the explanation and the PR.  I have some more questions, though.

`exceptionOptions` doesn't specify a `filterId`.  Maybe it works purely by exception path name, but in the screenshot, how does VS get the list of exception names that it shows?  I don't see a DAP request for this.

For `breakMode` == `never` -- why is this preferable to simply not setting an exception breakpoint at all?  That's the part I didn't understand -- why a client would ever be in the situation where it needs to do this.

**Comment by tromey** [comment]
Maybe some context would help here...

gdb can catch Ada exceptions and C++ exceptions.  It can do some filtering based on type name (which we could improve if it would help implement DAP).

The IDE would like to set exception breakpoints.  In C++, literally any object can be thrown, so there's no way to enumerate these.  Ada is more restrictive, but there still isn't a way to enumerate all possible exception names.

Nevertheless, we'd like the IDE to provide a way for users to specify which exceptions should cause a stop.  I had thought `exceptionOptions` was that way, but without `filterId` I don't see how it could differentiate between the different languages (right now gdb uses `exceptionBreakpointFilters` to do this differentiation).

**Comment by connor4312** [comment]
> For breakMode == never -- why is this preferable to simply not setting an exception breakpoint at all? That's the part I didn't understand -- why a client would ever be in the situation where it needs to do this.

This can be used if a parent in the tree `always` breaks but the client wishes to exclude a specific leaf/subtree from that behavior.

> exceptionOptions doesn't specify a filterId. Maybe it works purely by exception path name, but in the screenshot, how does VS get the list of exception names that it shows? I don't see a DAP request for this.

I believe this is provided by the language service, though I don't know much about specific mechanics there. VS Code doesn't implement `exceptionOptions`. As you say, enumerating them would be pretty hard as a simple DA without also being a language server, so maybe that's a request for LSP.

Something I do in the JavaScript debugger is that I have a 'magic' `error` variable in conditions (that I describe in the capabilities exceptionBreakpointsFilter response) that a user can see if, for example `error.name === 'MyErrorClass'`. Perhaps something along those lines would work for your scenario.

**Comment by tromey** [comment]
> Something I do in the JavaScript debugger is that I have a 'magic' error variable in conditions (that I describe in the capabilities exceptionBreakpointsFilter response) that a user can see if, for example error.name === 'MyErrorClass'. Perhaps something along those lines would work for your scenario.

Yeah, we can do that.  This kind of amounts to an adapter-specific extension, because the IDE will have to know that for this adapter, this form of filtering is appropriate.  Internally we're discussing this, though, with the other option being some local extension.
