### ISSUE TITLE
Ordering of launch, setBreakpoints, and configurationDone

### ISSUE THREAD

**Issue by tromey** [microsoft/debug-adapter-protocol#452]
The diagram on the overview page shows the client sending `setBreakpoints`, then `configurationDone`, and only at the end a `launch`.

My gdb adapter implemented this in the wrong way, assuming that `launch` would be send before `configurationDone`, and so the latter is what actually causes the inferior to run.  (I overlooked the or misread the diagram...)

However, looking at this now, I don't see how this is intended to work.  As far as I can tell, only the `launch` or `attach` operations provide any way for the IDE to tell the debugger which executable to examine.  Without this information, though, error-checking of something like `setBreakpoints` is basically impossible.

The section "Configuring breakpoint and exception behavior" seems to try to address this issue, but I find it a bit vague.

I would appreciate a clarification here.  Is it expected that the IDE communicate the executable via some out-of-band approach, like a command-line argument?  Or is it appropriate to add an extension to the `initialize` request to indicate the executable to use?  Or is the sequence supposed to be something like `launch`, then debugger sends `initialized` event, and *then* configuration?

**Comment by connor4312** [comment]
Your interpretation of the diagram is right. There's no out of bound signalling, nor should the client indicate add anything extra in the initialize request.

Adapters can update the state of breakpoints asynchronously via the [breakpoint](https://microsoft.github.io/debug-adapter-protocol/specification#Events_Breakpoint) event. What many adapters do is initially respond to the breakpoint request indicating the breakpoint is unverified with `verified: false`, then once the program is launched and the breakpoint binds, send a followup `breakpoint` event with its new state.

**Comment by AnthonyLeonardoGracio** [comment]
Hello @connor4312! I am working on the implementation of DAP on [GNAT Studio](https://github.com/AdaCore/gnatstudio)'s side, working with @tromey. 

Your proposal looks ok to me (i.e: fully rely on `breakpoint` events to know which breakpoints were found/not found) but it would be great if it could be explicitly written in the documentation, probably describing a little example in the `breakpoint` event's documentation, something like that.

**Comment by connor4312** [comment]
I opened a PR with some clarification 🙂
