### ISSUE TITLE
Add a `bytes` range to the DataBreakpointInfo Request

### ISSUE THREAD

**Issue by connor4312** [microsoft/debug-adapter-protocol#455]
> Splitting off from https://github.com/microsoft/debug-adapter-protocol/issues/445

One feature from the authors of the request include the ability to set breakpoints for a range of memory:

<img width="414" alt="image" src="https://github.com/microsoft/debug-adapter-protocol/assets/2230985/12016da1-2c68-4d0b-a5d8-444b41446f0a">

The "event points" map pretty well onto DAP [data breakpoints](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_DataBreakpointInfo), except data breakpoints can only be set for singular variables in the protocol.

To allow a range to be set, we need a corresponding capability

```ts
interface Capability {
  // ... in addition to exisitng properties:

  /**
   * The debug adapter supports padding `length` in the `DataBreakpoint` request.
   */
  supportsDataBreakpointBytes?: boolean;
```

Then there may be an additional field in the info request, which specifies the number of bytes following the address in which the debugger should stop:

```ts
interface DataBreakpointInfoArguments {
  // ... in addition to exisitng properties:

  /**
   * Clients may set this variable only if the `supportsDataBreakpointBytes`
   * capability is true.
   * 
   * Clients may pass this to request a reference to a range of memory rather
   * than a single variable or expression. Data breakpoints set using the
   * resulting data ID request that the debugger pauses within the range of
   * memory starting at address of the variable or expression,
   * and extending `bytes` exclusive bytes.
   * 
   * Treated as a hex value if prefixed with `0x`, or as a decimal value
   * otherwise.
   */
  bytes?: string;
````

**Comment by gregg-miskelly** [comment]
`dataBreakpointInfo` is really about asking a debug adapter to provide a description of how to set a data breakpoint on a variable. In this scenario, it doesn't seem like there is a variable involved -- it seems like the user is really inputting an address, size, and access settings.

Questions:
1. Can we come up with a standard set of properties for 'access settings'? Or do we really need a custom request (like launch arguments)?
2. Instead of extended `dataBreakpointInfo`, should we just extend [`DataBreakpoint`](https://github.com/microsoft/debug-adapter-protocol/blob/5ed0ddffe07221694cab6571771b66015f1e6f30/debugAdapterProtocol.json#L3734) so that when a new capability is present, `dataId` can have some special value (empty string?) and then there is a new field that carries additional properties about the address range?

**Comment by kkistm** [comment]
I agree with @gregg-miskelly about `DataBreakpointInfo` usage. Two fields from this interface, `variableReference` and `frameId`, are not useful for data breakpoints.
What about to introduce `DataRangeBreakpoint` or `MemoryRangeBreakpoing` interfaces, inspired by `DataBreakpoint` but tailored to the specific case? With a corresponding `set*()` method?

**Comment by markgoodchild** [comment]
I agree with @kkistm that making the interface more precise makes the purpose easier to understand and its usage cleaner.

**Comment by connor4312** [comment]
Thanks for the feedback. How about we introduce an alternative request, like `DataAddressBreakpointInfo`, with arguments

```ts
interface DataAddressBreakpointInfoArguments {
  /**
   * The address of the data for which to obtain breakpoint information.
   * Treated as a hex value if prefixed with `0x`, or as a decimal value
   * otherwise.
   */
  address: string;

  /**
   * If passed, requests breakpoint information for an exclusive byte range
   * rather than a single address. The range extends the given number of `bytes`
   * from the start `address`.
   * 
   * Treated as a hex value if prefixed with `0x`, or as a decimal value
   * otherwise.
   */
  bytes?: number
}
```

The response is identical to the [`DataBreakpointInfo`](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_DataBreakpointInfo) response, allowing the resulting `dataId` to interop with the existing `SetDataBreakpoints` request.

Of course this comes with a capability.

```ts
interface Capability {
  // ... in addition to existing properties:

  /**
   * The debug adapter supports the `dataAdressBreakpointInfo` request.
   */
  supportsDataAddressInfo?: boolean;
```

**Comment by kkistm** [comment]
@connor4312, the proposition about `DataAddressBreakpointInfo` sounds good for me, keeping in mind that additional properties could be added as needed.

**Comment by ZequanWu** [comment]
[Do we also wan](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_DataBreakpointInfo) says "If `variablesReference` isn't specified, this can be an expression." in `DataBreakpointInfoArguments`'s `name` field. If this request is added, does this mean the name could not be an expression anymore? If no, we still need the number of bytes to watch from expression.

**Comment by connor4312** [comment]
This was finished in https://github.com/microsoft/debug-adapter-protocol/pull/461

@ZequanWu see that PR for what we ended up doing, let us know if you have any feedback. Thanks!

**Comment by ZequanWu** [comment]
Oh, I saw the new request `DataAddressBreakpointInfo` has two fields: `address` and `bytes`. Then my question might be another issue:  For `name` in `DataBreakpointInfoArguments`, it could be an expression if `variablesReference` is not specified, like `${variable} + ${offset}`. How would the debugger know how many bytes to watch from the starting address evaluated from the expression in this case?

**Comment by connor4312** [comment]
We don't specify that an adapter should treat a numeric return value from an expression in `name` as a pointer to that address. A common implementation may be expecting some pointer-type result from the name and breaking either on that specific address or size of the data that was pointed to. An adapter or debugger could implement this in any number of ways. In a JavaScript runtime, there may be no notion of memory addresses at all and only object identity.

While a little roundabout it's possible to get the address of a variable via its `memoryReference`, which one could use to use the new range request to set a custom range of bytes for a variable

**Comment by ZequanWu** [comment]
> A common implementation may be expecting some pointer-type result from the name and breaking either on that specific address or size of the data that was pointed to.

I think it's common the pointer-type result from the name is a `void*` type which doesn't tell the underlying pointee's type information and size information in C/C++. In this case, the best we can do is to set the size to watch to the pointer size which might not always be the case.

**Comment by connor4312** [comment]
Reopening for discussion.

If we were to do it that way, we'd need some additional flagging for the debugger to treat the `name` as a numeric value. It's a bit of an overload, but we cannot make it optional as that would be backwards-incompatible.

```ts
interface DataBreakpointInfoArguments {
  /**
   * Reference to the variable container if the data breakpoint is requested for
   * a child of the container. The `variablesReference` must have been obtained
   * in the current suspended state. See 'Lifetime of Object References' in the
   * Overview section for details.
   */
  variablesReference?: number;

  /**
   * The name of the variable's child to obtain data breakpoint information for.
   * If `variablesReference` isn't specified, this can be an expression.
   * If `asAddress` is specified, this is a memory address: interpreted as a
   * hex value if prefixed with `0x`, or a decimal value otherwise.
   */
  name: string;

  /**
   * Clients may set this variable only if the `supportsDataBreakpointBytes`
   * capability is true.
   * 
   * Clients may pass this to request a reference to a range of memory rather
   * than a single address. Data breakpoints set using the resulting data ID
   * request that the debugger pauses within the range of memory extending
   * `bytes` from the address or variable specified by `name`.
   * 
   * Treated as a hex value if prefixed with `0x`, or as a decimal value
   * otherwise.
   */
  bytes?: number;

  /**
   * If `true`, the `name` is a memory address and the debugger should interpret.
   * 
   * Clients may set this variable only if the `supportsDataBreakpointBytes`
   * capability is true.
   */
  asAddress?: boolean;

  /**
   * When `name` is an expression, evaluate it in the scope of this stack frame.
   * If not specified, the expression is evaluated in the global scope. When
   * `variablesReference` is specified, this property has no effect.
   */
  frameId?: number;
}
```

The downside of this is that there is less support for "address-only" properties, but otherwise it's also a nice solution and solves the issue you mention.

**Comment by ZequanWu** [comment]
Do we need the extra field `asAddress`? 

Given "If `variablesReference` isn't specified, this can be an expression." for `name`, an expression could be a numeric value (decimal or hex) representing the address, right?

**Comment by connor4312** [comment]
I think `asAddress` is preferable so that DA's don't have to try to pattern match what they're being given. In common lisp for example, `0x123` is also a valid variable name, so it would be impossible to differentiate when taking input from a client.

**Comment by connor4312** [comment]
After playing around with this a bit, I prefer the new proposal in https://github.com/microsoft/debug-adapter-protocol/issues/455#issuecomment-1949333721. I'm going to back my previous changes out of the upcoming DAP release and put a PR in with that proposal for next month's release to allow time for additional discussion.
