### ISSUE TITLE
Clarification of the meaning of '?' in a request

### ISSUE THREAD

**Issue by tromey** [microsoft/debug-adapter-protocol#456]
We got a bug report against the gdb DAP implementation.  You can see the thread here: https://sourceware.org/pipermail/gdb/2024-January/051056.html

The bug seems to be that the client in this case sends:
```
{"arguments": null, "command": "configurationDone", "seq": 2, "type":  "request"}
```
My question is -- is this valid?  The `configurationDone` request does say:
```
interface ConfigurationDoneRequest extends Request {
  command: 'configurationDone';

  arguments?: ConfigurationDoneArguments;
}
```
However, the real meaning of the `?` does not seem to be spelled out anywhere.  Is `null` an allowable value here?  I wrote the gdb adapter to assume that optional values would simply be omitted -- but it's no problem to change if `null` is valid.

I think it would be good to be explicit about this.

**Comment by connor4312** [comment]
No, this is not valid. The point of truth for DAP is its JSON schema (draft 4). In JSON schema, null is not a valid replacement for optional object properties. You can test this in any [JSON scheme validator](https://www.jsonschemavalidator.net/) by trying to validate `{"foo":null}` with a schema like.

```
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type":"object",
    "properties": { "foo": { "type": "string" } }
}
``

(It is also not a valid replacement for object properties in TypeScript, which is how the interfaces are shown on the specification page)

This is a bug in the client.

**Comment by connor4312** [comment]
No, this is not valid. The point of truth for DAP is its [JSON schema](https://github.com/microsoft/debug-adapter-protocol/blob/main/debugAdapterProtocol.json). In JSON schema, null is not a valid replacement for optional object properties. You can test this in any [JSON scheme validator](https://www.jsonschemavalidator.net/) by trying to validate `{"foo":null}` with a schema like.

```
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type":"object",
    "properties": { "foo": { "type": "string" } }
}
```

(It is also not a valid replacement for optional object properties in TypeScript, which is how the interfaces are shown on the specification page)

This is a bug in the client.
