### ISSUE TITLE
Is it always allowed to send requests that control execution?

### ISSUE THREAD

**Issue by GniLudio** [microsoft/debug-adapter-protocol#457]
It is obvious that some requests only make sense in times in when the debugee is not executing. (e.g. `Continue` or `StepIn`)
Some other requests only make sense when the debugee is running. (e.g. `Pause`)

So my question is if it is still allowed to send these requests in inappropriate moments?

**Comment by connor4312** [comment]
These should only be sent for threads / in a state where execution is stopped, though there is always the chance for a race condition where the DA sends a "stopped" event while the client simultaneously issues a "pause" request. Therefore DA's should handle requests that happen in invalid states gracefully.

**Comment by puremourning** [comment]
... and clients should gracefully handle failures of course ;)

**Comment by connor4312** [comment]
Let us know if you have other questions
