### ISSUE TITLE
OutputEvent variablesReference lifetime clarification

### ISSUE THREAD

**Issue by justarandomgeek** [microsoft/debug-adapter-protocol#459]
OutputEvent describes variablesReference as having lifetime of only the current suspended state. What is the correct lifetime for one emitted while running/not-suspended?

**Comment by connor4312** [comment]
The lifetime of these objects should generally be "as long as possible" -- though of course this is limited by the runtime. I suggest the following additional

> Variable references not related to the current suspended state, such as those from `evaluate` requests or in `output` events, should be preserved as long as feasible for the debug adapter so that the client may later introspect them.
