### ISSUE TITLE
Help needed : Disassembly a C/C++ frame (function)

### ISSUE THREAD

**Issue by royqh1979** [microsoft/debug-adapter-protocol#470]
In my DAP client, I want to disassembly a selected frame from the stack. A disassemble request need  "memoryReference" and "instructionCount" as the arguments. 

I can get the "memoryReference" from StackFrame's "instructionPointerReference", but where could I find the  "instructionCount" ?

Thanks for the reply!

**Comment by connor4312** [comment]
`instructionCount` is just how many instructions you want the adapter to return to you as a client. This is based on how your UI behaves, for example you might guesstimate this based on the window size and height of disassembled rows to get enough data to fill the user's screen.

**Comment by connor4312** [comment]
Let us know if you have other questions.
