### ISSUE TITLE
Add Remote and Snapshot debugging operations

### ISSUE THREAD

**Issue by PavelSosin** [microsoft/debug-adapter-protocol#48]
Add notifications used in remote debuggers and Cloud applications debuggers
They are used for debugging of application deployed to production cloud infrastructure
- Attach : all remote debuggers
- Set snap point : Microsoft Snapshot debugger for remote .Net debugging
- Set conditional Snap point
-  Inspect snapshot : Microsoft Snapshot debugger for remote .Net debugging, Google Stackdriver debugger
- Take-a-snapshort  Microsoft Snapshot debugger for remote .Net debugging, Google Stackdriver
- View snapshot - Microsoft Snapshot debugger for remote .Net debugging, Google Stackdriver debugger
- Clear snapshotMicrosoft Snapshot debugger for remote .Net debugging, Google Stackdriver debugger

**Comment by weinand** [comment]
Please see DAP's logpoint feature.
