### ISSUE TITLE
Debug Event which is responsible for loading source file in Editor

### ISSUE THREAD

**Issue by sujatha2206** [microsoft/debug-adapter-protocol#480]
I am working on the debug adapter extension .I want to implement a feature that changes debugger program with out stopping the debugging.I am using source reference to stream content from backend and initial content is populated successfully.
I using the loadedsource event with the changed flag ,But it's not updated the content.
Which event is responsible for loading source using source reference in editor?

**Comment by connor4312** [comment]
Using the `changed` flag is the right thing to do from the debugger's perspective. If your editor does not support that flag, I suggest opening an issue on them. I don't think your scenario requires any changes to the debug protocol. Thanks!
