### ISSUE TITLE
[Question][Feature request] is it able to integrate to monaco editor?

### ISSUE THREAD

**Issue by EVS-ganesh** [microsoft/debug-adapter-protocol#488]
I am doing an editor with debugger option so I will need this feature. can you able to do this?

**Comment by connor4312** [comment]
Debugging isn't in the scope of the monaco editor. It's a text editor without any knowledge of debugging or debug lifecycles.

**Comment by EVS-ganesh** [comment]
> Debugging isn't in the scope of the monaco editor. It's a text editor without any knowledge of debugging or debug lifecycles.

"The Debug Adapter Protocol (DAP) defines the abstract protocol used between a development tool (e.g. IDE or editor) and a debugger."
here editor means which editor and is there any way to use it with editor?

**Comment by connor4312** [comment]
Here is a list of known DAP clients: https://microsoft.github.io/debug-adapter-protocol/implementors/tools/

**Comment by EVS-ganesh** [comment]
> Here is a list of known DAP clients: https://microsoft.github.io/debug-adapter-protocol/implementors/tools/

only these can be integrated with DAP?

**Comment by connor4312** [comment]
Sure, you can implement a DAP client that uses the monaco editor.
