### ISSUE TITLE
Reopening / clarification of #452

### ISSUE THREAD

**Issue by tromey** [microsoft/debug-adapter-protocol#497]
Hi.  We recently got a bug report against gdb asking that the configuration / launch logic be reimplemented (again).  The bug is here: https://sourceware.org/bugzilla/show_bug.cgi?id=32090

This logic was originally redone in response to the clarifications in #452 (thank you).

However, that bug now points out that there was a different, earlier clarification to the launch process hidden away here: https://github.com/microsoft/vscode/issues/4902#issuecomment-368583522 ... but apparently not incorporated into the spec.

In particular the user is asking that gdb implement the "late case" in the above -- a scenario where, IIUC, a `launch` request is held and not responded to until after `configurationDone`.

Is this a supported / relevant scenario?  If so, I think it should be documented in the spec.  It would also be great to have some guidance as to which scenario adapters should support, and which ones clients could or should assume (or how they can even detect this).

**Comment by connor4312** [comment]
Thanks for digging that up, I hadn't seen that before -- 2018 was before my time :)

I agree we should clarify the specification here. I only now realize the diagram on [the overview](https://microsoft.github.io/debug-adapter-protocol/overview) page previously referenced _does_ 'include' this, but only by a very sneaky grey box on the left-hand side to represent an asynchonrous process 🙂 

<img width="305" alt="image" src="https://github.com/user-attachments/assets/97d3b508-bb5d-4820-8e47-54b0e518be2d">
