### ISSUE TITLE
linesStartAt1 versus StackFrame

### ISSUE THREAD

**Issue by tromey** [microsoft/debug-adapter-protocol#519]
`StackFrame` says:
```
   * The line within the source of the frame. If the source attribute is missing
   * or doesn't exist, `line` is 0 and should be ignored by the client.
```
However, this seems to be ambiguous if the client says `linesStartAt1=False`.  In this situation, `line` can validly be `0`.

I don't know what the best fix is here.  Maybe changing the invalid value to `-1`?

I think there are similar situations elsewhere involving column numbers.

**Comment by tromey** [comment]
I think I read this too hastily, since if the source doesn't exist, the line number doesn't really matter anyway.  So I guess the possible overlap here just doesn't matter.

**Comment by connor4312** [comment]
yea, the wording is slightly awkward here, but it doesn't matter too much. Afaik there's no language that has a specialized integer type for "nonzero integers" so I don't think the ambiguity would cause any de/serialization failure.
