### ISSUE TITLE
Attach request parameters shall contain, at least, URL 

### ISSUE THREAD

**Issue by PavelSosin** [microsoft/debug-adapter-protocol#52]
Every Web resource shall have URL. Otherwise nobody sees it
I installed recent VSCode version. It looks and sounds like 100% Web IDE which uses Browser based UI. Browser can communicate with something only it has URL. WebIDE utilizes several LSP servers via providing common WS server-side layer which is used for communication between Web Client and server. Server can be implemented as exe but WS server-side layer totally hides this fact from client. Eclipse/Che architecture assumes that every side-car has URL.Every Docker container gets URL, at least IP from local daemon. to every IP can be assigned DNS name, i.e. URL. To debug nodejs using Chrome development tools user shall config nodejs instance as URL in Chrome development tools for nodejs configuration. PID can't be used in any remote debugging scenario because PID of remote computer is meaningless at client side is meaningless. PID is volatile and can't be a part of statefull debugging session. From other side URL tables are native part of any WebIDE context and can be easily managed. Even browser has enough options to store such tables in the scope of session.
DAP and LSP are built on top WebSocket. or WebSocket URL is must.

**Comment by puremourning** [comment]
>DAP and LSP are built on top WebSocket.

Is it? Looks like JSON RPC over STDIO to me. Nothing to do with websockets.
