### ISSUE TITLE
Specification: Server capabilities arguments clarification

### ISSUE THREAD

**Issue by PavelSosin** [microsoft/debug-adapter-protocol#53]
ServercapabilitiesArguments says:
/**
   * Determines in what format paths are specified. The default is 'path', which is the native format.
   * Values: 'path', 'uri', etc.
   */
  pathFormat?: string;

Why resource uri format of files is a part of DAP?
Working with Windows path format in browser is headache. Mixture of POSIX and Windows resource formats in the same different parts of the IDE will make user crazy. absolute file path contradicts both Workspace and Remote Workspace concept - artifact path always is based related workspace root. Maybe somebody saw in visualStudio, Eclipse or Chrome navigator Views C: or backslashes? It will take more time to explain to single user how to work in Windows and Unix and remote workspace. then adopt implementation to protocol. Especially when NodeJS offers built-in support.
Client ID is very important part of afinity mechanism. It ensures securyty. Remote debugging is very dangerous to debuggee process. Hijacked  debugging session opens unlimited access to all resources used by debuggee.  no explanation is given in specification!   
Please, be precise and consistent in the backbone protocol definition.

**Comment by int19h** [comment]
@PavelSosin Please stop spamming this repository. There are people subscribed to notifications on it, who work on debuggers that actually use all these things that are "unneeded" or "wrong" in shipping product code, today, and who need to track it, and various items in it, to keep up with the evolution of the protocol. Your comments here are not only irrelevant - they are actively distracting.
