### ISSUE TITLE
Question: why Debugger UI needs language related capabilities?

### ISSUE THREAD

**Issue by PavelSosin** [microsoft/debug-adapter-protocol#55]
I don't understand why Debugger client needs detailed purely language dependent server capabilities?
When developer uses IDE for development of certain type of project using certain language toolchain  he/she needs full toolchain: tokenizer for editor, validator, builder and debugger. Only debugger looks at debugger server capabilities. From Other hand every language uses own low-level protocol for debugging: jdwp, nodeinspector, etc. This protocol either supports certain operations or not. HANA debugger server has nothing to say about dissasembly or memory access capability. The configuration is purely static based on development language and , optionally, project type in the case when the same same language with some variation is used in different types of projects (typescript SAP UI5 vs typescript nodejs). The extended determination  is implemented in SAP WebIDE without any LSP and debugger server capability check.
Only server implementation related capabilities need some information from server like 1 step completion vs. 2 step completion vs with resolve. I know only one use-case when such option is supported - jdt based java LSP.
runtime capabilities reflection will dramatically complicate UI implementation: the core IDE editor 
is not necessary extensible like VS Monaco editor as it is stated in Monaco documentation and its implementation can be tightly coupled with certain protocols: Monaco with LSP, GNU GDB WebUI editor with  GDB server protocol. Adoption of Monaco to GDB or SAPUI5 Editor control to GDB can be extremely expensive but never used  by real-world developers because they never use assembly or C in their daily life.

**Comment by puremourning** [comment]
> never used by real-world developers because they never use assembly or C in their daily life.

I use both in my daily life. And I’m in the real world.

**Comment by PavelSosin** [comment]
So, this expensive Debugger Client UI extension will be dedicated specially to you. I afraid you have to wait GA of this feature very long time. GNU GDB Web UI which looks perfectly is available for you just now.

**Comment by puremourning** [comment]
Why on earth would i want to use a web UI for debugging? Either way, a key advantage of a language agnostic protocol is that it means i can have the same first class experience for all of the many languages and runtimes that i use in my editor of choice which, apparently surprisingly, isn't a web browser.

I think we need to accept that there is a use case for debugging on real machines, even if they are VMs, and even if they are in "the cloud". When you're stepping through some native code, then being able to see memory and registers is a real honest genuine use case, and is likely to be implemented by debuggers (or debug adapters) which are tailored for that case, such as gdb/lldb etc.

If you're only writing python or node or javascipt in a sandbox or whatever, then don't use or implement the features, but can we avoid campaigning against useful features ? Remember that the teams that build the web browser, web servers, switches, OSes and other infrastructure that are used in context also need to debug software and can also benefit from consistent IDEs.

I don't think these features were targetted at me, not least because they existed long before i was old enough to use them.

**Comment by PavelSosin** [comment]
@puremourning  Sorry, DAP protocol is defined in such way - to support any kind of debugging and the only feasible option today is to use Browser as UI. There is no need in any kind of protocol for local debugging. Please read the latest Microsoft VSCode release announcement which emphasizes VSCode cloud capabilities and interoperatability with Azure. RedHat, the current owner of eclipse, already took Eclipse to cloud as Eclipse/Che. Try to catch old desktop Visual studio until Microsoft will not take it to the native Microsoft environment - Azure.   
Microsoft offers you the option to localize you development landscape - you can use WSL under Windows to run both Client and Server on the same laptop.

**Comment by PavelSosin** [comment]
@puremourning Backlogs of all serious development tools providers are open for searching and submitting of customer proposals. The shape of popular development tools is not the result of voting in Facebook. These tools are shaped by very professional Product Owners and UX specialists. They are constantly listening all real user arguments and build teams backlog according added value and precise effort evaluation. All proposed extensions can be offered via corresponding marketplaces if they complain Product standards. Most necessary features will reach Limited Availability and General Availability first!

**Comment by puremourning** [comment]
> only feasible option today is to use Browser as UI

I respectfully disagree.

> There is no need in any kind of protocol for local debugging

I respectfully disagree.

> Please read the latest Microsoft VSCode release announcement which emphasizes VSCode cloud capabilities and interoperatability with Azure

I don't see the relevance. Microsoft continue to provide first class development environments for native code. 

> RedHat, the current owner of eclipse, already took Eclipse to cloud as Eclipse/Che

Again, I don't see the relevance. RedHat's business plan is not directly relevant to this discussion, nor would I consider myself qualified to comment on it.

> Microsoft offers you the option to localize you development landscape - you can use WSL under Windows to run both Client and Server on the same laptop

None of these technologies are relevant to this. There's a very large user base which neither uses Windows nor laptops.

> Backlogs of all serious development tools providers are open for searching and submitting of customer proposals

Let's assume that's true, sure.

> The shape of popular development tools is not the result of voting in Facebook.

OK, sure.

> These tools are shaped by very professional Product Owners and UX specialists. They are constantly listening all real user arguments and build teams backlog according added value and precise effort evaluation. 

Excellent.

> All proposed extensions can be offered via corresponding marketplaces if they complain Product standards. Most necessary features will reach Limited Availability and General Availability first

I don't see the relevance.

**Comment by puremourning** [comment]
Apologies to the maintainers of this repo for this diversion. I won't respond further to this discussion so as to (attempt to) keep it on topic.

**Comment by PavelSosin** [comment]
As @puremourning  mentioned DAP shall be universally used communication protocol. Today "universally used" is translated into application architecture language as "serverless". The receipt how to use Microsoft VSCode as "serverless" development environment installed on single laptop is described in VSCode documentation: [Development Linux subsystedm on Windows ](https://code.visualstudio.com/docs/remote/wsl). I know from first hands that offering of non-cloud IDE is not on road-map of SAP and RedHat. Microsoft, RedHat and SAP are 1st hand adopters of DAP. Features which are not planned to be implemented by potential adopters in visible future will harm DAP adoption.

**Comment by PavelSosin** [comment]
@weinand All dynamically enabled and disabled options are very expensive in implementation. From my experience in last line development customer support I learned that 90%  of responses on customer issues are generated by 1st line customer support. The automatic response on the bug report _"Why I open assembly file in debugger the options like dissasembly and memory access are enabled in debugger menu but when I open java file they are disabled? I opened this issue on the previous release but Microsoft ignores it and can't resolve this issue 6 mo.nths. Please elevate this issue"_ shall be These options are enabled for certain languages as it is described in documentation on page nnn. This configuration can't be changed by user. **Dot**  . Explanations like "Because this command is not supported by Debugger server which is used to fulfill your request. It can't do it due to unrelated to Microsoft reasons. Such explanations are rarely accepted by users.
From this point of view static configurations of commands produce better user experience.

**Comment by weinand** [comment]
The Debug Adapter Protocol uses dynamic capabilities (aka feature flags) since day one. Changing this is not possible anymore.
