### ISSUE TITLE
Incorrectly typed attributes in DAP schema.

### ISSUE THREAD

**Issue by vadimcn** [microsoft/debug-adapter-protocol#62]
A number of attributes that represent various IDs are declared as "number", whereas most of the time they are types as "integer" (which makes sense IMO).   This creates problems for automatically generated bindings in strongly-typed languages, because "number" is translated to a floating point type, whereas "integer" - to an int64.

Here's a list of the ones I've found (there may be more):
https://github.com/microsoft/debug-adapter-protocol/blob/0f9909d5259388bc252049a5d9fb97deae73af6b/debugAdapterProtocol.json#L311
https://github.com/microsoft/debug-adapter-protocol/blob/0f9909d5259388bc252049a5d9fb97deae73af6b/debugAdapterProtocol.json#L559
https://github.com/microsoft/debug-adapter-protocol/blob/0f9909d5259388bc252049a5d9fb97deae73af6b/debugAdapterProtocol.json#L563
https://github.com/microsoft/debug-adapter-protocol/blob/0f9909d5259388bc252049a5d9fb97deae73af6b/debugAdapterProtocol.json#L1698
https://github.com/microsoft/debug-adapter-protocol/blob/0f9909d5259388bc252049a5d9fb97deae73af6b/debugAdapterProtocol.json#L1702
https://github.com/microsoft/debug-adapter-protocol/blob/0f9909d5259388bc252049a5d9fb97deae73af6b/debugAdapterProtocol.json#L1706
https://github.com/microsoft/debug-adapter-protocol/blob/0f9909d5259388bc252049a5d9fb97deae73af6b/debugAdapterProtocol.json#L2010
https://github.com/microsoft/debug-adapter-protocol/blob/0f9909d5259388bc252049a5d9fb97deae73af6b/debugAdapterProtocol.json#L2014
https://github.com/microsoft/debug-adapter-protocol/blob/0f9909d5259388bc252049a5d9fb97deae73af6b/debugAdapterProtocol.json#L2018
https://github.com/microsoft/debug-adapter-protocol/blob/0f9909d5259388bc252049a5d9fb97deae73af6b/debugAdapterProtocol.json#L2093
https://github.com/microsoft/debug-adapter-protocol/blob/0f9909d5259388bc252049a5d9fb97deae73af6b/debugAdapterProtocol.json#L2097
https://github.com/microsoft/debug-adapter-protocol/blob/0f9909d5259388bc252049a5d9fb97deae73af6b/debugAdapterProtocol.json#L2101
https://github.com/microsoft/debug-adapter-protocol/blob/0f9909d5259388bc252049a5d9fb97deae73af6b/debugAdapterProtocol.json#L2781

**Comment by int19h** [comment]
Related to #40

**Comment by weinand** [comment]
I've created PR https://github.com/microsoft/debug-adapter-protocol/pull/63 for the change and asked for a review by the team that owns a generator for strongly-typed languages.

**Comment by weinand** [comment]
Addressed by PR #63
