### ISSUE TITLE
Ability to pause without a current thread

### ISSUE THREAD

**Issue by joelday** [microsoft/debug-adapter-protocol#66]
Currently it appears that the `pause` command requires a `threadId` property. It also appears that VSCode, for example, will not send that command if there is no thread selected in the Call Stack panel.

My debug adapter is for a runtime that does not have a single persistent 'thread' throughout the life of the debug session. The threads that do run do so with a unique id and usually for a very short period of time. (<1s) So, at any given time, the Call Stack panel is usually empty.

I would like to pause at any time whether there is a selected thread or not, where the `stop` event can fire whenever the next execution comes along. (Unsure if I can send multiple `stop` events, one without a `threadId` and one with when execution is actually stopped somewhere.) I would also like to be able to un-pause before that `stop` event is fired.

**Comment by puremourning** [comment]
> So, at any given time, the Call Stack panel is usually empty.

I think the protocol says that 5ere must always be 1 thread even if it is fake.

**Comment by PavelSosin** [comment]
I think that the meaning of Thread term is not so obvious. Not all programming languages use threads. Even I develop code in programmind language which supports threads like Java or Go I can use Functional Reactive programming and don't care about threads. Support of threads is specific language feature. I strongly support the idea of implicit thread.

**Comment by weinand** [comment]
yes, if a debug adapter does not support multiple threads, it must implement the `threads` request and return a single "fake" thread. 
see "Supporting threads" section in the DAP overview.
