### ISSUE TITLE
Unclear about the state retention of variablesReference

### ISSUE THREAD

**Issue by mickaelistria** [microsoft/debug-adapter-protocol#75]
I'm trying to implement `setVariable` in my IDE, and have a question that arise from trying the node-debug2 debug adapter.
Mainly, it's not clear from the specification whether `variablesReference` are supposed to: change with time (ie same variable would have a different variablesReference when the children change) or whether they're fixed for the model and the content change anyway.
To put it another way, if I ask for `variables` with same `variablesReference` as input, am I always supposed to get the same result, or is the result likely to change if the state of the application changed.
Or, to put it another way, what's the proper way to refresh one variable? If I so `setVariable` and then ask `variable` with the same `variableReferences`, am I expected to see the difference on the last return of the `variables` request.

I think this needs to be clarified in the spec as it influences how client or debug adapter are supposed to orchestrate their request/responses.

Thanks in advance.

**Comment by weinand** [comment]
(Variable)References need only be valid while the target (thread) is stopped. As soon as the (target) continues, they don't need to be valid.

From the DAP client (aka UI frontend) perspective that means that references are dropped and no longer used after the target has continued.

For the debug adapter that means either that it can start reusing reference values after the target has stopped, but it does not have to (in case it want to use UUIDs as references).

**Comment by mickaelistria** [comment]
Ok,thanks, that helps a lot!
A correlate question: what avout setVariable? After callibg it,is the variableReference supposed to be the same and content changed, or is the «parent» variable reference discarded?
