### ISSUE TITLE
supportsStepBack cannot be set during launchRequest

### ISSUE THREAD

**Issue by maziac** [microsoft/debug-adapter-protocol#88]
Hi,
I would like to set the supportsStepBack capability during the call to launchRequest.
At the moment I can do it only during initializeRequest.
The problem is:
For my debug-adapter the reverse debug capability should be configurable in the launch.json (of the debugged program).
I.e. a user of the debugger should have the option to disable it e.g. to have less buttons on the screen in vscode or maybe because he is never using the reverse debug capability.

However launch.json is only available in the 'args' of the launchRequest but not of the initializeRequest.

So I require some possibility to set/clear the step-back capability from the launchRequest.

**Comment by int19h** [comment]
`CapabilitiesEvent` allows for this, although there's no guarantee that the frontend would honor it for this particular property.

**Comment by maziac** [comment]
Thanks, thats' working. Great.
