### ISSUE TITLE
Not all integer properties are indicated as such in the spec

### ISSUE THREAD

**Issue by KamasamaK** [microsoft/debug-adapter-protocol#90]
Since the auto-generated spec file uses TypeScript to represent the protocol, the `integer` type from the schema is converted to `number`. This is mitigated in some places that have "The value should be less than or equal to 2147483647 (2^31 - 1)." as part of the comment, but that is not universally included for `integer` properties.

Continuation from #62 and #63

**Comment by jonahgraham** [comment]
It seems reasonable for items such as `threadId`s, `line`, `column` to be stored as 32-bit integer, other items such as `ReadMemoryResponse.unreadableBytes`, `ReadMemoryArguments.offset`, `DisassembleArguments.offset` do refer to 64-bit address spaces. The `ReadMemoryArguments.memoryReference` is already a string, so perhaps it is reasonable to limit such `offset`s and `unreadableBytes` to 32-bit values.

Thank you for for providing clarification.

**Comment by jonahgraham** [comment]
@weinand can we get a confirmation that these should be 32-bits in the spec? LSP4J wants to do a release soon and we are assuming that based on the referenced issues that this is indeed supposed to be 32-bit integers.

**Comment by KamasamaK** [comment]
I would recommend following the convention used by the Language Server Protocol of defining a [custom base type in the TypeScript spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#baseTypes).

This way, it will be clear that the type is `integer` instead of `number` without having to refer to the docblock.

The type definition copied from LSP:
```typescript
/**
 * Defines an integer number in the range of -2^31 to 2^31 - 1.
 */
export type integer = number;
```

**Comment by KamasamaK** [comment]
I realize I may not have been clear in my description, but the change in #357 doesn't solve the issue I was trying to describe. This wasn't about just specifying what `integer` means in the protocol.

Basically, the source of truth seems to be the [JSON schema](https://microsoft.github.io/debug-adapter-protocol/debugAdapterProtocol.json). But the [published specification](https://microsoft.github.io/debug-adapter-protocol/specification) that is auto-generated from that schema does not properly retain the `integer` types. Since `integer` is not a native type in TypeScript, I was recommending making a custom type as LSP does.
