### ISSUE TITLE
Specify unit of column offsets

### ISSUE THREAD

**Issue by puremourning** [microsoft/debug-adapter-protocol#91]
Forgive me if I missed it, but I couldn't see a specification for the values of column offsets.

Examples:

* Breakpoint locations
* Stack trace locations
* Completion request (assuming the `text` item is utf-8 encoded, what does the `column` items count ? bytes? or codepoints ? ).

I realise with LSP there is a bit of a fiasco with it being specified as UTF16 code units, is that also the assumption here?

**Comment by weinand** [comment]
Today columns offsets are based on a UTF-16 string representation. 
But we are planning to make this negotiable via DAP capabilities.

**Comment by puremourning** [comment]
So they are like LSP; UTF-8 code units?

**Comment by weinand** [comment]
No, LSP is based on a UTF-16 string representation which means that it uses 16-bit code units.
And DAP uses the same.

**Comment by puremourning** [comment]
Sorry yes I typod  I mean utf 16 code units. 

Thanks for the clarification.
