### ISSUE TITLE
Code repository is empty

### ISSUE THREAD

**Issue by kesongyue** [microsoft/debug-adapter-protocol#95]
Is this debug-adapter-protocol open source? Why this code repository is empty, just a few files.

**Comment by weinand** [comment]
The debug adapter protocol is open source, but it only consists of this [JSON schema file](https://github.com/microsoft/debug-adapter-protocol/blob/gh-pages/debugAdapterProtocol.json).

You can find "SDKs" that implement the protocol for different languages [here](https://microsoft.github.io/debug-adapter-protocol/implementors/sdks/).

**Comment by kesongyue** [comment]
Cool ! Thanks!
