### ISSUE TITLE
Weird comments for the latest commit in the repo

### ISSUE THREAD

**Issue by rpeshkov** [microsoft/debug-adapter-protocol#97]
Looking at the repo I noticed that there are 2 comments for the last commit
<img width="1007" alt="Screenshot 2020-02-21 at 16 51 48" src="https://user-images.githubusercontent.com/701068/75050035-83875480-54cb-11ea-9a9c-b18172d808b0.png">

If you go to the comments, you'll see that there are link to the website https://avgle.com
<img width="852" alt="Screenshot 2020-02-21 at 16 52 07" src="https://user-images.githubusercontent.com/701068/75050145-b7fb1080-54cb-11ea-889c-c83cc3721f22.png">

I didn't try to open the link, but it looks malicious and completely unrelated to this repository.

**Comment by weinand** [comment]
Thanks for reporting. I've deleted the comments.
