### ISSUE TITLE
Canonical URLs in web pages are wrong

### ISSUE THREAD

**Issue by gfx** [microsoft/debug-adapter-protocol#98]
for example: view-source:https://microsoft.github.io/debug-adapter-protocol/

> `<link rel="canonical" href="https://microsoft.github.io/debug-adapter-protocol//debug-adapter-protocol/">`

where https://microsoft.github.io/debug-adapter-protocol//debug-adapter-protocol/ is 404.

**Comment by weinand** [comment]
I cannot reproduce.

**Comment by connor4312** [comment]
I can see this with OP's intructions, I we should still fix this.
